const DISTRICT_CNS = {
  id: 'cns',
  name: 'CNS quarter',
  theme_line: 'Mind & nerves · sedation, fits, mood, anaesthetics, opioids',
  walkthrough: `The CNS quarter crowns the highest hill in Pharma City — a labyrinth of cobbled lanes lit by oil-lamps that flicker and swell with every synaptic wave. From the central crossroads you can peer down on all the other districts below; up here the air is thinner, the silences more complete, and the consequences of getting the chemistry wrong more sudden. Six wards radiate outward like spokes: the Sleep Quarter (its windows permanently frosted, warm amber light pooling under low doorframes), the Mood Gardens (a walled park where the flowers bloom or wilt depending on monoamine rainfall), the Asylum Walls (tall grey stone, iron gates, faint rhythmic chanting), the Seizure Chapel (a vaulted nave trembling with suppressed electrical charge), the Tremor Walk (cobbles worn smooth by patients who shuffle here daily), and the Anaesthetic Theatre (a circular glass rotunda behind which figures slip in and out of stillness). Streets end abruptly in fog at the district's edges so each ward feels sealed from the next — a deliberate architecture of compartmentalised consciousness.

Deeper into the hill, where the oil-lamps give way to guttering red torches, lies the Opium Den: a subterranean courtyard paved with smooth river-stones, its archways draped with damp silk, the air thick with the sweet weight of the mu receptor. Above ground the Pharmacy-Hill Clock Tower keeps time for the entire quarter — its pendulum swings in exact 90-minute cycles to mark the REM rhythm, and when it strikes midnight the oil-lamps dim throughout the Sleep Quarter simultaneously. Every building on the hill is named for the drug it houses; every drug carries the exact latitude of its action inscribed above its doorway; every wall bears a contraindication plaque in raised iron lettering, because on the CNS hill a dosing error can silence the clock altogether.`,
  palette: { ground: 0x6B7FA3, accent: 0xC8A96E, water: 0x3A5278 },
  position: { x: -20, z: -40 },
  classification: {
    sources: [
      {
        label: 'G&G 14e',
        cite: 'ch. 16–24',
        groups: [
          { heading: 'A. Sedative-hypnotics & anxiolytics', groups: [
            { heading: 'Benzodiazepines', drugs: ['Diazepam', 'Lorazepam', 'Midazolam', 'Alprazolam'] },
            { heading: 'Non-benzodiazepine hypnotics (Z-drugs)', drugs: ['Zolpidem', 'Zaleplon', 'Eszopiclone'] },
            { heading: 'Azapirones', drugs: ['Buspirone'] },
            { heading: 'Barbiturates', drugs: ['Phenobarbital'] },
            { heading: 'Melatonergic', drugs: ['Ramelteon'] },
            { heading: 'Benzodiazepine antagonist', drugs: ['Flumazenil'] },
          ]},
          { heading: 'B. Antidepressants', groups: [
            { heading: 'SSRIs', drugs: ['Fluoxetine', 'Sertraline', 'Escitalopram', 'Paroxetine'] },
            { heading: 'SNRIs', drugs: ['Venlafaxine', 'Duloxetine'] },
            { heading: 'Tricyclic antidepressants (TCAs)', drugs: ['Amitriptyline', 'Imipramine', 'Nortriptyline'] },
            { heading: 'MAO inhibitors', drugs: ['Phenelzine', 'Tranylcypromine', 'Moclobemide'] },
            { heading: 'Atypical antidepressants', drugs: ['Bupropion', 'Mirtazapine', 'Trazodone', 'Vortioxetine'] },
          ]},
          { heading: 'C. Antipsychotics', groups: [
            { heading: 'Typical (first-generation)', drugs: ['Haloperidol', 'Chlorpromazine', 'Fluphenazine', 'Trifluoperazine'] },
            { heading: 'Atypical (second-generation)', drugs: ['Clozapine', 'Olanzapine', 'Risperidone', 'Quetiapine', 'Aripiprazole', 'Ziprasidone', 'Lurasidone'] },
          ]},
          { heading: 'C2. Mood stabilisers', groups: [
            { heading: 'Antimanic / mood stabiliser', drugs: ['Lithium'] },
          ]},
          { heading: 'D. Antiepileptics (by clinical use)', groups: [
            { heading: 'Generalized tonic-clonic & partial seizures', drugs: ['Phenytoin', 'Carbamazepine', 'Valproate', 'Lamotrigine', 'Levetiracetam', 'Topiramate', 'Lacosamide', 'Brivaracetam', 'Perampanel'] },
            { heading: 'Gabapentinoids (focal seizures / neuropathic pain)', drugs: ['Gabapentin', 'Pregabalin'] },
            { heading: 'Absence seizures', drugs: ['Ethosuximide', 'Valproate'] },
            { heading: 'Status epilepticus', drugs: ['Lorazepam', 'Diazepam', 'Phenytoin', 'Fosphenytoin'] },
          ]},
          { heading: 'E. Antiparkinsonian drugs', groups: [
            { heading: 'Dopamine precursor', drugs: ['Levodopa + Carbidopa'] },
            { heading: 'Dopamine agonists', drugs: ['Pramipexole', 'Ropinirole', 'Bromocriptine'] },
            { heading: 'MAO-B inhibitors', drugs: ['Selegiline', 'Rasagiline'] },
            { heading: 'COMT inhibitors', drugs: ['Entacapone', 'Tolcapone'] },
            { heading: 'Anticholinergics', drugs: ['Trihexyphenidyl', 'Benztropine'] },
            { heading: 'Antiviral / NMDA antagonist', drugs: ['Amantadine'] },
          ]},
          { heading: 'F. General anaesthetics', groups: [
            { heading: 'Intravenous', drugs: ['Propofol', 'Ketamine', 'Thiopentone', 'Etomidate', 'Midazolam', 'Dexmedetomidine'] },
            { heading: 'Inhalational', drugs: ['Sevoflurane', 'Isoflurane', 'Desflurane', 'Nitrous oxide', 'Halothane'] },
          ]},
          { heading: 'G. Local anaesthetics', groups: [
            { heading: 'Amides', drugs: ['Lidocaine', 'Bupivacaine', 'Ropivacaine'] },
            { heading: 'Esters', drugs: ['Procaine', 'Cocaine', 'Benzocaine', 'Tetracaine'] },
          ]},
          { heading: 'H. Opioid analgesics', groups: [
            { heading: 'Strong agonists', drugs: ['Morphine', 'Fentanyl', 'Methadone', 'Pethidine', 'Oxycodone'] },
            { heading: 'Mild-to-moderate agonists', drugs: ['Codeine', 'Tramadol'] },
            { heading: 'Partial agonist / mixed agonist-antagonist', drugs: ['Buprenorphine', 'Pentazocine', 'Nalbuphine'] },
            { heading: 'Antagonists', drugs: ['Naloxone', 'Naltrexone'] },
          ]},
          { heading: 'I. Key concepts & principles', groups: [
            { heading: 'CNS neurotransmitters & receptors', drugs: [
              'GABA-A receptor (Cl⁻ channel; BZD vs barbiturate sites)',
              'GABA-B receptor (Gi/o GPCR; baclofen)',
              'Glutamate receptors (NMDA & AMPA)',
              'Opioid receptors (μ, κ, δ)',
            ]},
            { heading: 'Dopamine pathways & antipsychotic effects', drugs: [
              'Four dopamine pathways (mesolimbic, mesocortical, nigrostriatal, tuberoinfundibular)',
              'Typical vs atypical antipsychotics',
            ]},
            { heading: 'Affective & seizure principles', drugs: [
              'Monoamine hypothesis of depression',
              'Seizure classification (focal vs generalised; absence, tonic-clonic, status)',
              'Mechanisms of antiepileptic drug action',
            ]},
            { heading: 'Anaesthesia & analgesia principles', drugs: [
              'Stages & depth of general anaesthesia (Guedel) & MAC',
              'Local anaesthetic mechanism (use-dependent Na⁺ channel block)',
              'Parkinson disease: dopamine–acetylcholine balance',
              'Opioid tolerance, dependence & withdrawal',
            ]},
          ]},
        ],
      },
      {
        label: 'KDT 8e/9e',
        cite: 'ch. 27–36',
        groups: [
          { heading: 'A. Sedative-hypnotics & anxiolytics', groups: [
            { heading: 'Benzodiazepines', drugs: ['Diazepam', 'Lorazepam', 'Midazolam', 'Alprazolam'] },
            { heading: 'Newer non-benzodiazepine hypnotics (Z-drugs)', drugs: ['Zolpidem', 'Zaleplon', 'Eszopiclone'] },
            { heading: 'Azapirones', drugs: ['Buspirone'] },
            { heading: 'Barbiturates', drugs: ['Phenobarbital'] },
            { heading: 'Melatonin receptor agonist', drugs: ['Ramelteon'] },
            { heading: 'Benzodiazepine antagonist', drugs: ['Flumazenil'] },
          ]},
          { heading: 'B. Antidepressants', groups: [
            { heading: 'Selective serotonin reuptake inhibitors (SSRIs)', drugs: ['Fluoxetine', 'Sertraline', 'Escitalopram', 'Paroxetine'] },
            { heading: 'Serotonin-noradrenaline reuptake inhibitors (SNRIs)', drugs: ['Venlafaxine', 'Duloxetine'] },
            { heading: 'Tricyclic antidepressants (TCAs)', drugs: ['Amitriptyline', 'Imipramine', 'Nortriptyline'] },
            { heading: 'Monoamine oxidase inhibitors (MAOIs)', drugs: ['Phenelzine', 'Tranylcypromine', 'Moclobemide'] },
            { heading: 'Atypical antidepressants', drugs: ['Bupropion', 'Mirtazapine', 'Trazodone', 'Vortioxetine'] },
          ]},
          { heading: 'C. Antipsychotics (neuroleptics)', groups: [
            { heading: 'Typical (first-generation)', drugs: ['Haloperidol', 'Chlorpromazine', 'Fluphenazine', 'Trifluoperazine'] },
            { heading: 'Atypical (second-generation)', drugs: ['Clozapine', 'Olanzapine', 'Risperidone', 'Quetiapine', 'Aripiprazole', 'Ziprasidone', 'Lurasidone'] },
          ]},
          { heading: 'C2. Mood stabilisers', groups: [
            { heading: 'Antimanic / mood stabiliser', drugs: ['Lithium'] },
          ]},
          { heading: 'D. Antiepileptic drugs (by clinical use)', groups: [
            { heading: 'Generalized tonic-clonic & partial seizures', drugs: ['Phenytoin', 'Carbamazepine', 'Valproate', 'Lamotrigine', 'Levetiracetam', 'Topiramate', 'Lacosamide', 'Brivaracetam', 'Perampanel'] },
            { heading: 'Gabapentinoids (focal seizures / neuropathic pain)', drugs: ['Gabapentin', 'Pregabalin'] },
            { heading: 'Absence seizures', drugs: ['Ethosuximide', 'Valproate'] },
            { heading: 'Status epilepticus', drugs: ['Lorazepam', 'Diazepam', 'Phenytoin', 'Fosphenytoin'] },
          ]},
          { heading: 'E. Antiparkinsonian drugs', groups: [
            { heading: 'Dopamine precursor', drugs: ['Levodopa + Carbidopa'] },
            { heading: 'Dopaminergic agonists', drugs: ['Pramipexole', 'Ropinirole', 'Bromocriptine'] },
            { heading: 'MAO-B inhibitors', drugs: ['Selegiline', 'Rasagiline'] },
            { heading: 'COMT inhibitors', drugs: ['Entacapone', 'Tolcapone'] },
            { heading: 'Central anticholinergics', drugs: ['Trihexyphenidyl', 'Benztropine'] },
            { heading: 'Amantadine', drugs: ['Amantadine'] },
          ]},
          { heading: 'F. General anaesthetics', groups: [
            { heading: 'Intravenous', drugs: ['Propofol', 'Ketamine', 'Thiopentone', 'Etomidate', 'Midazolam', 'Dexmedetomidine'] },
            { heading: 'Inhalational', drugs: ['Sevoflurane', 'Isoflurane', 'Desflurane', 'Nitrous oxide', 'Halothane'] },
          ]},
          { heading: 'G. Local anaesthetics', groups: [
            { heading: 'Amides', drugs: ['Lidocaine', 'Bupivacaine', 'Ropivacaine'] },
            { heading: 'Esters', drugs: ['Procaine', 'Cocaine', 'Benzocaine', 'Tetracaine'] },
          ]},
          { heading: 'H. Opioid analgesics', groups: [
            { heading: 'Strong agonists', drugs: ['Morphine', 'Fentanyl', 'Methadone', 'Pethidine', 'Oxycodone'] },
            { heading: 'Mild-to-moderate agonists', drugs: ['Codeine', 'Tramadol'] },
            { heading: 'Partial / mixed agonist-antagonist', drugs: ['Buprenorphine', 'Pentazocine', 'Nalbuphine'] },
            { heading: 'Antagonists', drugs: ['Naloxone', 'Naltrexone'] },
          ]},
          { heading: 'I. Key concepts & principles', groups: [
            { heading: 'CNS neurotransmitters & receptors', drugs: [
              'GABA-A receptor (Cl⁻ channel; BZD vs barbiturate sites)',
              'GABA-B receptor (Gi/o GPCR; baclofen)',
              'Glutamate receptors (NMDA & AMPA)',
              'Opioid receptors (μ, κ, δ)',
            ]},
            { heading: 'Dopamine pathways & antipsychotic effects', drugs: [
              'Four dopamine pathways (mesolimbic, mesocortical, nigrostriatal, tuberoinfundibular)',
              'Typical vs atypical antipsychotics',
            ]},
            { heading: 'Affective & seizure principles', drugs: [
              'Monoamine hypothesis of depression',
              'Seizure classification (focal vs generalised; absence, tonic-clonic, status)',
              'Mechanisms of antiepileptic drug action',
            ]},
            { heading: 'Anaesthesia & analgesia principles', drugs: [
              'Stages & depth of general anaesthesia (Guedel) & MAC',
              'Local anaesthetic mechanism (use-dependent Na⁺ channel block)',
              'Parkinson disease: dopamine–acetylcholine balance',
              'Opioid tolerance, dependence & withdrawal',
            ]},
          ]},
        ],
      },
    ],
  },
  drugs: [

    // ─── SEDATIVE-HYPNOTICS & ANXIOLYTICS (ch. 19) ──────────────────────────

    {
      id: 'diazepam',
      district: 'cns',
      building: 'the long-burning Amber Lantern lodge of the Sleep Quarter',
      class: 'Benzodiazepine; long-acting sedative-hypnotic and anxiolytic',
      mechanism: 'Positive allosteric modulator of GABA-A receptors: binds the α/γ subunit interface between α1, α2, α3, or α5 subunits and the γ2 subunit, increasing the frequency of Cl⁻ channel opening in response to GABA (without activating the channel in GABA\'s absence). Does not increase channel conductance or opening duration — that is the barbiturate mechanism. Active metabolites (nordiazepam, temazepam, oxazepam) extend the clinical effect; half-life of parent compound 20–100 hours.',
      adverse_effects: 'CNS depression: sedation, impaired psychomotor performance, anterograde amnesia; respiratory depression (additive with other CNS depressants); physical dependence and withdrawal syndrome (rebound anxiety, insomnia, seizures) on abrupt discontinuation; tolerance; paradoxical disinhibition in children and elderly; hangover effect next day due to long half-life.',
      clinical_use: 'Acute anxiety and panic disorder; status epilepticus (IV); acute alcohol withdrawal (prevents withdrawal seizures and delirium tremens); skeletal muscle spasm; procedural sedation; pre-anaesthetic medication.',
      memory_hook: 'The Amber Lantern burns for days — diazepam\'s half-life is so long the lamp never fully dims, which is useful for continuous alcohol withdrawal but causes hangover sedation the morning after.',
      source: 'G&G 14e, ch. 19',
      high_yield: true,
    },
    {
      id: 'lorazepam',
      district: 'cns',
      building: 'the liver-side inn at the crossroads of the Sleep Quarter',
      class: 'Benzodiazepine; intermediate-acting, direct hepatic conjugation',
      mechanism: 'Positive allosteric modulator of GABA-A (same mechanism as diazepam). Undergoes direct glucuronide conjugation (phase II only) in the liver — no CYP450-dependent oxidation. This means no active metabolites, predictable kinetics in liver disease, and no drug–drug interactions from CYP induction. Half-life 10–20 hours.',
      adverse_effects: 'Sedation; anterograde amnesia (reliable, used therapeutically before procedures); respiratory depression; physical dependence; withdrawal on abrupt cessation; pain on IV injection (propylene glycol vehicle).',
      clinical_use: 'Status epilepticus (preferred IV benzodiazepine in many protocols); alcohol withdrawal — preferred over diazepam in hepatic impairment; acute anxiety; procedural sedation and amnesia; pre-operative medication.',
      memory_hook: 'The liver-side inn accepts guests whose livers can\'t metabolise the long-burning lantern — lorazepam skips CYP oxidation, so even a failing liver can clear it by direct conjugation.',
      source: 'G&G 14e, ch. 19',
      high_yield: true,
    },
    {
      id: 'midazolam',
      district: 'cns',
      building: 'the short-stay procedure room at the Sleep Quarter gate',
      class: 'Benzodiazepine; short-acting, water-soluble, IV/IM',
      mechanism: 'Positive allosteric modulator of GABA-A. Water-soluble at acidic pH (formulation pH); ring closes at physiological pH to form lipid-soluble active form → rapid CNS penetration. Short half-life (1.5–3 hours) and rapid redistribution. Produces reliable anterograde amnesia.',
      adverse_effects: 'Respiratory depression (significant; needs airway equipment); hypotension; profound amnesia; paradoxical agitation in children; respiratory depression potentiated by opioids — this combination has caused deaths in procedural sedation without monitoring.',
      clinical_use: 'Procedural sedation (endoscopy, cardioversion, minor surgery); induction of anaesthesia; status epilepticus (buccal or intranasal midazolam in children; IV in adults); ICU sedation.',
      memory_hook: 'The short-stay procedure room clears out quickly — midazolam acts fast and wears off fast, leaving behind a reliable gap in the patient\'s memory of the procedure.',
      source: 'G&G 14e, ch. 19',
      high_yield: true,
    },
    {
      id: 'flumazenil',
      district: 'cns',
      building: 'the antidote station at the gate of the Sleep Quarter',
      class: 'Benzodiazepine receptor antagonist; competitive',
      mechanism: 'Competitively antagonises all BZD agonists (and partial agonists and inverse agonists) at the BZD binding site of GABA-A receptors. Has negligible intrinsic activity. Half-life only 1 hour — much shorter than most BZDs — so re-sedation can occur when flumazenil wears off before the BZD is cleared.',
      adverse_effects: 'Precipitation of acute withdrawal seizures in BZD-dependent patients (potentially life-threatening). Re-sedation (short half-life). Anxiety, agitation, palpitations on reversal. Does NOT reverse barbiturates or other CNS depressants.',
      clinical_use: 'Reversal of BZD-induced sedation after procedural sedation or anaesthesia; BZD overdose (titrate carefully; multiple doses may be needed; must monitor for re-sedation).',
      memory_hook: 'The antidote station springs open the locked GABA-A door — but its key only lasts an hour, so the BZD fog can roll back in after the shift is over.',
      source: 'G&G 14e, ch. 19',
      high_yield: true,
    },
    {
      id: 'zolpidem',
      district: 'cns',
      building: 'the selective slumber cottage at the edge of the Sleep Quarter fog',
      class: 'Z-drug; non-benzodiazepine GABA-A modulator (imidazopyridine)',
      mechanism: 'Binds the BZD site on GABA-A receptors but with selectivity for α1 subunit-containing receptors (which mediate sedation and amnesia). Weaker anxiolytic and anticonvulsant effects than BZDs owing to lower α2/α3 activity. Short half-life (2–3 hours); promotes sleep onset. Undergoes extensive hepatic metabolism; metabolite zolpidem carboxylic acid is inactive.',
      adverse_effects: 'Residual sedation; complex sleep behaviours (sleep-driving, sleep-eating, sleepwalking without memory); anterograde amnesia; dependence (less than BZDs but present); rebound insomnia on withdrawal; hallucinations.',
      clinical_use: 'Short-term management of insomnia (particularly sleep-onset insomnia). Not indicated for anxiety or seizure disorders.',
      memory_hook: 'The slumber cottage targets only the α1 door — just enough GABA-A to induce sleep without the full BZD spectrum, but the fog can make you wander the cobblestones in your sleep.',
      source: 'G&G 14e, ch. 19',
      high_yield: true,
    },
    {
      id: 'buspirone',
      district: 'cns',
      building: 'the calm reading room above the Mood Gardens border',
      class: '5-HT1A partial agonist; azapirone anxiolytic',
      mechanism: 'Partial agonist at presynaptic and postsynaptic 5-HT1A receptors; also has weak D2 partial agonist activity. Does NOT bind GABA-A receptors — no cross-tolerance with BZDs, no withdrawal syndrome, no sedation, no respiratory depression, no dependence. Anxiolytic effect requires 2–4 weeks of consistent dosing (unlike immediate BZD effect).',
      adverse_effects: 'Dizziness; headache; nausea; nervousness; no sedation (advantage); no impairment of psychomotor performance; no withdrawal; no abuse potential.',
      clinical_use: 'Generalised anxiety disorder (GAD) — preferred when sedation or dependence is a concern; not useful for acute panic or phobic anxiety (insufficient acute effect); not for alcohol withdrawal.',
      memory_hook: 'The calm reading room has no lock on GABA-A — buspirone walks in through the 5-HT1A door instead, arriving quietly after two to four weeks rather than instantly like the BZD lantern.',
      source: 'G&G 14e, ch. 19',
      high_yield: true,
    },

    // ─── ANTIDEPRESSANTS (ch. 18) ────────────────────────────────────────────

    {
      id: 'fluoxetine',
      district: 'cns',
      building: 'the long-remembered Serotonin Greenhouse in the Mood Gardens',
      class: 'SSRI; selective serotonin reuptake inhibitor',
      mechanism: 'Blocks SERT (serotonin transporter SLC6A4), preventing reuptake of 5-HT from the synapse. Little affinity for other monoamine transporters or receptors. Exceptionally long half-life (1–4 days for parent; 4–16 days for active metabolite norfluoxetine) — least likely of SSRIs to cause discontinuation syndrome; most problematic for drug interactions due to strong CYP2D6 inhibition.',
      adverse_effects: 'GI upset (nausea, diarrhoea); sexual dysfunction (most common reason for discontinuation); insomnia; headache; initial anxiety/activation; SIADH (especially in elderly); weight changes (typically neutral then slightly positive). SEROTONIN SYNDROME when combined with MAOIs, SNRIs, tramadol, linezolid, or other serotonergic agents — requires ≥2-week washout before switching to an MAOI (≥5 weeks from fluoxetine specifically due to long half-life).',
      clinical_use: 'Major depressive disorder; generalised anxiety disorder; panic disorder; OCD; bulimia nervosa; PMDD.',
      memory_hook: 'The Serotonin Greenhouse retains its warmth for weeks after closing — norfluoxetine stays in the bloodstream so long that switching to an MAOI must wait five weeks, not just two.',
      source: 'G&G 14e, ch. 18',
      high_yield: true,
    },
    {
      id: 'sertraline',
      district: 'cns',
      building: 'the steady-rain garden pavilion of the Mood Gardens',
      class: 'SSRI; selective serotonin reuptake inhibitor',
      mechanism: 'Blocks SERT with high selectivity. Moderate half-life (~26 hours; no clinically significant active metabolites unlike fluoxetine). Mild inhibition of CYP2D6 and CYP3A4 — fewer drug interactions than fluoxetine or paroxetine. Often considered the SSRI with the most favourable side-effect and interaction profile.',
      adverse_effects: 'GI upset; diarrhoea (somewhat higher incidence than other SSRIs); sexual dysfunction; insomnia or somnolence; SIADH. SEROTONIN SYNDROME risk with MAOIs — ≥2-week washout required before or after MAOI use.',
      clinical_use: 'Major depressive disorder; PTSD (first-line); panic disorder; social anxiety disorder; OCD; PMDD. Often preferred in cardiac patients (most evidence for safety post-MI).',
      memory_hook: 'The steady-rain pavilion delivers consistent serotonin without the dramatic long-lingering echo of fluoxetine — sertraline is the reliable workhorse of the SSRI ward.',
      source: 'G&G 14e, ch. 18',
      high_yield: true,
    },
    {
      id: 'venlafaxine',
      district: 'cns',
      building: 'the dual-pump mill at the centre of the Mood Gardens',
      class: 'SNRI; serotonin-norepinephrine reuptake inhibitor',
      mechanism: 'Inhibits both SERT and NET (norepinephrine transporter). At lower doses primarily serotonergic; norepinephrine reuptake inhibition becomes significant at higher doses. Active metabolite desvenlafaxine also contributes. Half-life ~5 hours (parent), ~11 hours (desvenlafaxine); XR formulation allows once-daily dosing.',
      adverse_effects: 'Nausea; hypertension (dose-dependent, from NE effect); tachycardia; sexual dysfunction; diaphoresis; discontinuation syndrome (worse than SSRIs — taper carefully). SEROTONIN SYNDROME with MAOIs — ≥2-week washout required.',
      clinical_use: 'Major depressive disorder; generalised anxiety disorder; social anxiety disorder; panic disorder; diabetic peripheral neuropathy; fibromyalgia pain; stress urinary incontinence (off-label).',
      memory_hook: 'The dual-pump mill grinds with both the serotonin and norepinephrine wheels — the extra norepinephrine pump adds pain relief and blood-pressure liability that the single-pump SSRIs lack.',
      source: 'G&G 14e, ch. 18',
      high_yield: true,
    },
    {
      id: 'bupropion',
      district: 'cns',
      building: 'the no-smoking statute hall at the upper edge of the Mood Gardens',
      class: 'NDRI; norepinephrine-dopamine reuptake inhibitor',
      mechanism: 'Inhibits NET and DAT (dopamine transporter); weak nicotinic acetylcholine receptor antagonist (contributes to smoking cessation efficacy). No serotonergic activity — minimal sexual dysfunction and no serotonin syndrome risk. LOWERS SEIZURE THRESHOLD in a dose-dependent manner — serious risk in predisposed patients.',
      adverse_effects: 'Insomnia; agitation; dry mouth; headache; tachycardia; SEIZURES (CONTRAINDICATED in patients with seizure disorders, eating disorders [anorexia nervosa, bulimia — electrolyte abnormalities lower seizure threshold], or abrupt alcohol/BZD withdrawal). No weight gain (often causes weight loss). No sexual dysfunction.',
      clinical_use: 'Major depressive disorder (particularly when sexual dysfunction or weight gain from other antidepressants is a concern); smoking cessation (reduces craving and withdrawal symptoms); ADHD (second-line); seasonal affective disorder.',
      memory_hook: 'The no-smoking statute hall uses dopamine and norepinephrine to ban cigarettes, but its electrified corridors are CONTRAINDICATED in patients who seize — the seizure threshold plunges with eating disorders or epilepsy.',
      source: 'G&G 14e, ch. 18',
      high_yield: true,
    },
    {
      id: 'amitriptyline',
      district: 'cns',
      building: 'the three-curse monument at the gate of the Mood Gardens',
      class: 'TCA; tricyclic antidepressant — tertiary amine',
      mechanism: 'Blocks SERT and NET (primary antidepressant action). Also antagonises muscarinic receptors (anticholinergic ADRs), H1 histamine receptors (sedation, weight gain), α1 adrenoceptors (orthostatic hypotension), and voltage-gated sodium channels (cardiac toxicity; membrane stabilising effect — quinidine-like). Active metabolite nortriptyline has higher NET selectivity and fewer adverse effects.',
      adverse_effects: 'Anticholinergic: dry mouth, constipation, urinary retention, blurred vision, confusion in elderly. Sedation (H1). Orthostatic hypotension (α1). Weight gain. Cardiac: QTc prolongation, QRS widening (sodium channel block). OVERDOSE — the 3 C\'s: CARDIOTOXICITY (QRS widening, ventricular arrhythmias), CONVULSIONS, COMA. Treat overdose with IV sodium bicarbonate (narrows QRS). Narrow therapeutic index — potentially fatal in overdose.',
      clinical_use: 'Major depressive disorder (largely replaced by SSRIs but still used). More commonly now: neuropathic pain (diabetic neuropathy, post-herpetic neuralgia); migraine prophylaxis; fibromyalgia; enuresis in children.',
      memory_hook: 'The three-curse monument bears three plaques: Cardiotoxicity, Convulsions, Coma — the triad of TCA overdose. Sodium bicarbonate is carved as the antidote; the monument\'s narrow arch is the narrow therapeutic index.',
      source: 'G&G 14e, ch. 18',
      high_yield: true,
    },
    {
      id: 'phenelzine',
      district: 'cns',
      building: 'the tyramine-restricted tavern in the oldest alley of the Mood Gardens',
      class: 'MAOI; monoamine oxidase inhibitor — irreversible, non-selective',
      mechanism: 'Irreversibly inhibits both MAO-A (which degrades 5-HT and NE) and MAO-B (which degrades DA). Prevents breakdown of monoamine neurotransmitters → elevates 5-HT, NE, and DA. Irreversible — new MAO enzyme must be synthesised before normal function resumes (2 weeks). TYRAMINE REACTION: normally MAO in gut wall and liver metabolises dietary tyramine; with MAO inhibited, tyramine enters systemic circulation, triggers massive NE release → hypertensive crisis.',
      adverse_effects: 'TYRAMINE (CHEESE) REACTION: hypertensive crisis — headache, palpitations, neck stiffness, potentially fatal stroke (avoid all tyramine-rich foods: aged cheeses, cured meats, fermented products, red wine, beer). SEROTONIN SYNDROME with SSRIs, SNRIs, tramadol, meperidine — potentially fatal; ≥2-week washout on BOTH sides of transition. Orthostatic hypotension; weight gain; insomnia; hepatotoxicity.',
      clinical_use: 'Atypical depression (oversensitivity, reversed neurovegetative features); treatment-resistant depression; social anxiety disorder. Reserved for resistant cases due to dietary restrictions and drug interaction risk.',
      memory_hook: 'The tyramine-restricted tavern posts a long menu of forbidden cheeses at the door — MAO-A normally destroys tyramine in the gut, so without it, aged brie becomes a loaded hypertensive gun.',
      source: 'G&G 14e, ch. 18',
      high_yield: true,
    },

    // ─── ANTIPSYCHOTICS (ch. 16) ─────────────────────────────────────────────

    {
      id: 'haloperidol',
      district: 'cns',
      building: 'the high-security watchtower at the Asylum Walls',
      class: 'Typical antipsychotic; butyrophenone — high-potency D2 antagonist',
      mechanism: 'Potent competitive antagonist at D2 dopamine receptors in the mesolimbic pathway (antipsychotic effect), nigrostriatal pathway (EPS), tuberoinfundibular pathway (hyperprolactinaemia), and chemoreceptor trigger zone (antiemetic). Minimal H1, muscarinic, or α1 blockade at typical doses. High D2 affinity.',
      adverse_effects: 'EXTRAPYRAMIDAL SYMPTOMS (EPS): acute dystonia (early — hours to days; treat with benztropine or diphenhydramine); akathisia (restlessness); parkinsonism (days to months); tardive dyskinesia (months to years — orofacial involuntary movements; potentially irreversible). NEUROLEPTIC MALIGNANT SYNDROME (NMS): hyperthermia, rigidity, altered consciousness, autonomic instability — treat with dantrolene + bromocriptine. Hyperprolactinaemia (galactorrhoea, amenorrhoea, sexual dysfunction). QTc prolongation.',
      clinical_use: 'Schizophrenia; acute psychosis; delirium (IV/IM haloperidol — preferred in ICU); Tourette syndrome; intractable hiccups; refractory nausea and vomiting.',
      memory_hook: 'The high-security watchtower jams D2 so tightly that the mesolimbic pathway quiets — but the nigrostriatal pathway, also D2-dependent, develops EPS as collateral damage from the same lock.',
      source: 'G&G 14e, ch. 16',
      high_yield: true,
    },
    {
      id: 'chlorpromazine',
      district: 'cns',
      building: 'the sedating low-potency gatehouse at the Asylum Walls',
      class: 'Typical antipsychotic; phenothiazine — low-potency, broad receptor blockade',
      mechanism: 'Blocks D2 receptors (antipsychotic effect) but with relatively lower D2 affinity than haloperidol. Also extensively blocks H1 (sedation), muscarinic receptors (anticholinergic), and α1 adrenoceptors (orthostatic hypotension). Low D2 affinity → more sedation and less EPS than high-potency typicals.',
      adverse_effects: 'Sedation (H1); orthostatic hypotension (α1); anticholinergic (dry mouth, urinary retention, constipation); photosensitivity; CORNEAL AND LENS DEPOSITS with long-term use (slit-lamp examination required); skin pigmentation (slate-grey/purple); cholestatic jaundice; tardive dyskinesia (lower risk than high-potency); NMS (rare); QTc prolongation.',
      clinical_use: 'Schizophrenia; bipolar mania (historical); intractable hiccups; refractory nausea; pre-operative sedation. Largely replaced by atypicals but still used in low-resource settings.',
      memory_hook: 'The sedating gatehouse welcomes everyone into a drowsy haze — broad receptor blockade means plenty of side effects alongside the antipsychotic, and the corneal deposits are the long-term toll for residence.',
      source: 'G&G 14e, ch. 16',
      high_yield: true,
    },
    {
      id: 'clozapine',
      district: 'cns',
      building: 'the locked blood-count clinic inside the Asylum Walls',
      class: 'Atypical antipsychotic; dibenzodiazepine — high affinity D4 > D2',
      mechanism: 'Blocks D4, D2 (loose binding — "fast-off" hypothesis), D1, 5-HT2A, 5-HT2C, H1, muscarinic M1–M4, and α1 receptors. Weak D2 blockade and high 5-HT2A blockade explains atypical profile (fewer EPS). Most effective antipsychotic for treatment-resistant schizophrenia and suicidality in schizophrenia.',
      adverse_effects: 'AGRANULOCYTOSIS (1–2% — potentially fatal; MANDATORY absolute neutrophil count [ANC] monitoring at baseline, weekly for 6 months, then biweekly; drug must be stopped if ANC < 1000/μL). MYOCARDITIS (first 6–8 weeks). Weight gain and metabolic syndrome (most severe of all antipsychotics). Hypersalivation. Seizures (dose-dependent). Sedation. Orthostatic hypotension. CONTRAINDICATED in myelosuppressive conditions or history of clozapine-induced agranulocytosis.',
      clinical_use: 'Treatment-resistant schizophrenia (failed ≥2 adequate antipsychotic trials); suicidal ideation in schizophrenia or schizoaffective disorder (only antipsychotic with FDA approval for this). Clozapine REMS programme required.',
      memory_hook: 'The locked blood-count clinic requires a weekly passport stamped with ANC — clozapine cannot be dispensed without it, because agranulocytosis can kill before the next appointment.',
      source: 'G&G 14e, ch. 16',
      high_yield: true,
    },
    {
      id: 'olanzapine',
      district: 'cns',
      building: 'the weight-gain bakehouse inside the Asylum Walls',
      class: 'Atypical antipsychotic; thienobenzodiazepine',
      mechanism: 'Blocks D2 (moderate-high), 5-HT2A, H1, muscarinic, and α1 receptors. High 5-HT2A/D2 ratio contributes to atypical profile. Active metabolite 4-N-desmethyl olanzapine. Weight gain attributed to H1 and 5-HT2C blockade (increases appetite).',
      adverse_effects: 'Marked weight gain and metabolic syndrome (dyslipidaemia, insulin resistance, new-onset type 2 diabetes) — monitor weight, fasting glucose, and lipids. Sedation. Orthostatic hypotension. Anticholinergic. Low EPS. Low prolactin elevation. CONTRAINDICATED in demented elderly patients (increased stroke and mortality risk — black box warning applies to all atypicals for dementia-related psychosis).',
      clinical_use: 'Schizophrenia; acute mania and maintenance in bipolar disorder; combination with fluoxetine for bipolar depression; acute agitation (IM formulation); nausea and vomiting (off-label).',
      memory_hook: 'The weight-gain bakehouse hands out a metabolic toll to every resident — H1 and 5-HT2C blockade make the appetite insatiable, and the BMI climbs with every week on the ward.',
      source: 'G&G 14e, ch. 16',
      high_yield: true,
    },
    {
      id: 'risperidone',
      district: 'cns',
      building: 'the balanced-dose pavilion at the inner court of the Asylum Walls',
      class: 'Atypical antipsychotic; benzisoxazole',
      mechanism: 'High-potency antagonist at D2 and 5-HT2A receptors; also blocks α1, α2, and H1. At lower doses: 5-HT2A/D2 ratio favours atypical profile with fewer EPS; at HIGHER DOSES D2 blockade becomes proportionally dominant → EPS risk approaches that of typicals. Active metabolite paliperidone (9-OH-risperidone) is itself marketed as a separate antipsychotic.',
      adverse_effects: 'HYPERPROLACTINAEMIA (more pronounced than other atypicals due to poor BBB penetration by metabolite — galactorrhoea, amenorrhoea, sexual dysfunction). EPS at higher doses. Orthostatic hypotension. Weight gain (moderate). Metabolic effects (less than olanzapine). QTc prolongation.',
      clinical_use: 'Schizophrenia; schizoaffective disorder; bipolar mania (adjunct); irritability in autism spectrum disorder (paediatric). Long-acting injectable (LAI) formulation for adherence.',
      memory_hook: 'The balanced-dose pavilion works well at low doses but tips into the typical EPS zone at high doses — and the prolactin tap never fully closes, even at therapeutic levels.',
      source: 'G&G 14e, ch. 16',
      high_yield: true,
    },
    {
      id: 'aripiprazole',
      district: 'cns',
      building: 'the partial-signal relay station at the Asylum Walls perimeter',
      class: 'Atypical antipsychotic; D2/D3 partial agonist, 5-HT1A partial agonist, 5-HT2A antagonist',
      mechanism: 'Partial agonist at D2 and D3 receptors — acts as functional antagonist in hyperdopaminergic states (psychosis) and as functional agonist in hypodopaminergic states. This "dopamine system stabiliser" mechanism reduces EPS and avoids the prolactin elevation of full D2 antagonists. Also partial 5-HT1A agonist (anxiolytic, antidepressant) and 5-HT2A antagonist.',
      adverse_effects: 'Akathisia (may worsen at initiation — more common than with other atypicals). Nausea; insomnia; headache; anxiety. Minimal weight gain and metabolic effects. Minimal sedation. Low prolactin. Minimal QTc effect. Low EPS.',
      clinical_use: 'Schizophrenia; bipolar mania (monotherapy and adjunctive); adjunctive treatment of MDD; irritability in ASD; Tourette syndrome; agitation in schizophrenia (IM). Long-acting injectable formulations available.',
      memory_hook: 'The partial-signal relay station does not silence dopamine entirely — it turns the volume to the right level whether the circuit is too loud or too quiet, with minimal metabolic rent to pay.',
      source: 'G&G 14e, ch. 16',
      high_yield: true,
    },

    // ─── ANTIEPILEPTICS (ch. 17) ─────────────────────────────────────────────

    {
      id: 'phenytoin',
      district: 'cns',
      building: 'the zero-order kinetometer chapel in the Seizure Chapel nave',
      class: 'Antiepileptic; voltage-gated Na⁺ channel blocker',
      mechanism: 'Binds preferentially to the inactive (inactivated) state of voltage-gated Na⁺ channels and prolongs inactivation, reducing the frequency of high-frequency repetitive firing without affecting baseline neuronal activity. Membrane stabilisation limits seizure propagation. ZERO-ORDER (SATURABLE) KINETICS: at therapeutic concentrations, metabolism is saturated — small dose increments cause disproportionately large plasma level increases.',
      adverse_effects: 'DOSE-DEPENDENT CNS: nystagmus (first sign), diplopia, ataxia, drowsiness, confusion. Chronic: GINGIVAL HYPERPLASIA (common; counsel on oral hygiene); HIRSUTISM; peripheral neuropathy; osteomalacia (CYP induction → increased vitamin D metabolism). TERATOGEN: FETAL HYDANTOIN SYNDROME (cleft palate, cardiac defects, finger/nail hypoplasia, craniofacial abnormalities). ZERO-ORDER KINETICS → narrow therapeutic index; small dose changes cause large plasma level swings. IV: cardiac arrhythmias (propylene glycol vehicle) — use fosphenytoin IV instead. SJS (rare).',
      clinical_use: 'Focal and generalised tonic-clonic seizures; status epilepticus (IV fosphenytoin); trigeminal neuralgia (off-label); ventricular arrhythmias (historical).',
      memory_hook: 'The zero-order kinetometer chapel turns small increments into large plasma swings — phenytoin\'s saturable metabolism means adding one brick to the kiln can double the temperature, and the teratogen plaque above the door reads "fetal hydantoin syndrome."',
      source: 'G&G 14e, ch. 17',
      high_yield: true,
    },
    {
      id: 'carbamazepine',
      district: 'cns',
      building: 'the autoinduction forge on the Seizure Chapel hillside',
      class: 'Antiepileptic; voltage-gated Na⁺ channel blocker (iminodibenzyl)',
      mechanism: 'Blocks voltage-gated Na⁺ channels in the inactivated state (same as phenytoin). Also blocks some Ca²⁺ channels. AUTOINDUCTION: induces its own metabolism via CYP3A4 — plasma levels fall over the first weeks of therapy until autoinduction plateaus. Strong inducer of CYP3A4, CYP2C9 — reduces plasma levels of many drugs (oral contraceptives, warfarin, other AEDs, protease inhibitors).',
      adverse_effects: 'Sedation; diplopia; ataxia; HYPONATRAEMIA (SIADH, especially in elderly); aplastic anaemia (rare, but check CBC); AGRANULOCYTOSIS. STEVENS-JOHNSON SYNDROME (SJS/TEN): STRONGLY ASSOCIATED WITH HLA-B*1502 ALLELE in patients of Han Chinese, Thai, and other South/Southeast Asian descent — GENETIC SCREENING RECOMMENDED before prescribing in these populations.',
      clinical_use: 'Focal seizures and generalised tonic-clonic seizures; TRIGEMINAL NEURALGIA (first-line); bipolar disorder (mood stabiliser); glossopharyngeal neuralgia.',
      memory_hook: 'The autoinduction forge burns its own fuel — carbamazepine induction lowers its own levels and speeds the clearance of co-medications. The SJS plaque above the furnace names HLA-B*1502 as the trigger in Asian patients.',
      source: 'G&G 14e, ch. 17',
      high_yield: true,
    },
    {
      id: 'valproate',
      district: 'cns',
      building: 'the broad-spectrum archive of the Seizure Chapel',
      class: 'Antiepileptic; broad-spectrum — Na⁺ channel block + GABAergic + T-type Ca²⁺ inhibition',
      mechanism: 'Multiple mechanisms: (1) blocks voltage-gated Na⁺ channels; (2) increases GABA levels by inhibiting GABA transaminase and succinic semialdehyde dehydrogenase; (3) blocks T-type Ca²⁺ channels (relevant for absence seizures). Broad spectrum covers nearly all seizure types. Inhibits CYP2C9, UGT enzymes — increases levels of lamotrigine, phenobarbital, and other drugs.',
      adverse_effects: 'GI distress (take with food); HEPATOTOXICITY (potentially fatal fulminant hepatic failure, especially in children < 2 years, polytherapy, and metabolic disorders — check LFTs). PANCREATITIS. TERATOGENICITY: NEURAL TUBE DEFECTS (spina bifida, anencephaly) — highest teratogenic risk of all AEDs; FOLIC ACID SUPPLEMENTATION REQUIRED; avoid in women of childbearing potential if possible; also causes developmental delay and autism spectrum features. WEIGHT GAIN. Thrombocytopenia. Tremor. Hair loss (alopecia). POLYCYSTIC OVARIAN SYNDROME with long-term use.',
      clinical_use: 'Broad-spectrum AED: focal, generalised tonic-clonic, absence, myoclonic seizures; juvenile myoclonic epilepsy (first-line); bipolar disorder (mood stabiliser); migraine prophylaxis.',
      memory_hook: 'The broad-spectrum archive holds every seizure type — but the neural tube defect warning is embossed on the front cover: valproate in pregnancy means folic acid is mandatory and the risk of NTDs is the highest of all AEDs.',
      source: 'G&G 14e, ch. 17',
      high_yield: true,
    },
    {
      id: 'lamotrigine',
      district: 'cns',
      building: 'the slow-titration library beside the Seizure Chapel',
      class: 'Antiepileptic; voltage-gated Na⁺ channel blocker; also inhibits glutamate release',
      mechanism: 'Blocks voltage-gated Na⁺ channels (inactivated state) and possibly Ca²⁺ channels; inhibits presynaptic release of glutamate. Relatively broad spectrum. Metabolised by UGT (glucuronidation): VALPROATE inhibits UGT → plasma levels of lamotrigine double; enzyme-inducing AEDs (carbamazepine, phenytoin) increase clearance → levels fall. Titration must be very slow, especially when combined with valproate.',
      adverse_effects: 'STEVENS-JOHNSON SYNDROME (SJS) and toxic epidermal necrolysis (TEN) — RISK IS SIGNIFICANTLY INCREASED WITH RAPID TITRATION or when combined with valproate (which doubles plasma levels). Dizziness; diplopia; headache; rash (must distinguish benign rash from SJS — discontinue immediately for blistering, mucous membrane involvement, or widespread rash). Relatively weight-neutral; minimal cognitive effects.',
      clinical_use: 'Focal and generalised seizures; Lennox-Gastaut syndrome; absence seizures (adjunctive); BIPOLAR DEPRESSION (first-line maintenance for depressive episodes); PREGNANCY — relatively safer than valproate or carbamazepine.',
      memory_hook: 'The slow-titration library\'s front door rule: turn the pages one at a time — rush the titration or add valproate and the SJS rash blazes through the building like a fire.',
      source: 'G&G 14e, ch. 17',
      high_yield: true,
    },
    {
      id: 'levetiracetam',
      district: 'cns',
      building: 'the synaptic vesicle vault of the Seizure Chapel',
      class: 'Antiepileptic; SV2A ligand — unique mechanism',
      mechanism: 'Binds synaptic vesicle protein 2A (SV2A), which is involved in vesicle fusion and neurotransmitter exocytosis — exact mechanism by which this reduces seizure activity is not fully elucidated but likely modulates vesicle release. Does NOT block Na⁺ channels or affect GABA/glutamate directly. Broad spectrum. Renal excretion (dose adjustment in renal impairment). Minimal drug interactions (not CYP-metabolised).',
      adverse_effects: 'BEHAVIOURAL ADVERSE EFFECTS: irritability, aggression, depression, and psychosis (important; may require dose reduction or addition of pyridoxine/B6); somnolence; headache; dizziness. Relatively weight-neutral. No hepatotoxicity. No teratogenicity signal comparable to valproate.',
      clinical_use: 'Focal seizures (first-line adjunctive); juvenile myoclonic epilepsy; generalised tonic-clonic seizures; status epilepticus (IV levetiracetam increasingly used). Preferred in pregnancy (relatively safer than older AEDs).',
      memory_hook: 'The synaptic vesicle vault targets SV2A — an entirely different mechanism from the sodium channel chapel — but the price of residency is behavioural: irritability and aggression disturb the quiet wards.',
      source: 'G&G 14e, ch. 17',
      high_yield: true,
    },
    {
      id: 'ethosuximide',
      district: 'cns',
      building: 'the T-type calcium-channel chapel annex for absence seizures',
      class: 'Antiepileptic; T-type (low-threshold) Ca²⁺ channel blocker',
      mechanism: 'Selectively blocks T-type Ca²⁺ channels in thalamic relay neurons. Absence seizures are generated by abnormal 3 Hz spike-wave discharges driven by oscillatory activity in thalamocortical circuits, powered by T-type channels. Ethosuximide blocks this oscillatory rhythm without affecting Na⁺ channels (therefore NOT effective for tonic-clonic seizures).',
      adverse_effects: 'GI upset (nausea, vomiting, anorexia); sedation; headache; hiccups; SLE-like syndrome (rare); blood dyscrasias (rare — periodic CBC recommended). No teratogenicity data comparable to valproate or phenytoin.',
      clinical_use: 'ABSENCE SEIZURES (FIRST-LINE, especially if only absence seizures without tonic-clonic component) — narrow spectrum; valproate preferred if patient also has tonic-clonic seizures.',
      memory_hook: 'The T-type calcium annex is the only chapel door that opens for absence seizures — ethosuximide closes the thalamic T-channel oscillator that drives the 3 Hz absences, but it cannot see tonic-clonic seizures through its narrow keyhole.',
      source: 'G&G 14e, ch. 17',
      high_yield: true,
    },
    {
      id: 'topiramate',
      district: 'cns',
      building: 'the multi-mechanism corridor of the Seizure Chapel',
      class: 'Antiepileptic; multiple mechanisms — Na⁺ channel block, GABA-A enhancement, AMPA/kainate antagonism, carbonic anhydrase inhibition',
      mechanism: 'Four mechanisms: (1) blocks voltage-gated Na⁺ channels; (2) potentiates GABA-A (enhances Cl⁻ conductance); (3) antagonises AMPA/kainate (glutamate) receptors; (4) inhibits carbonic anhydrase II and IV (weak, but contributes to adverse effects). Broad-spectrum. Metabolised partly by CYP; inducing AEDs increase clearance.',
      adverse_effects: 'COGNITIVE IMPAIRMENT ("dopamax") — word-finding difficulties, mental slowing, psychomotor slowing. KIDNEY STONES (nephrolithiasis) — carbonic anhydrase inhibition alkalinises urine, reduces urinary citrate; avoid in patients with kidney stone history; hydration important. Weight loss (beneficial in some patients; mechanism includes carbonic anhydrase inhibition and appetite reduction). Paraesthesia (common). Metabolic acidosis (carbonic anhydrase). Acute closed-angle glaucoma (rare). Teratogen: cleft palate (caution in pregnancy).',
      clinical_use: 'Focal and generalised seizures; Lennox-Gastaut syndrome; migraine prophylaxis (FDA-approved); weight management in obesity (combined with phentermine in fixed-dose formulation).',
      memory_hook: 'The multi-mechanism corridor is powerful but foggy — cognitive slowing ("dopamax") blurs the residents\' thinking, and carbonic anhydrase inhibition paves the kidney stone pathway if fluids are neglected.',
      source: 'G&G 14e, ch. 17',
      high_yield: true,
    },

    // ─── ANTI-PARKINSON (ch. 21) ─────────────────────────────────────────────

    {
      id: 'levodopa_carbidopa',
      district: 'cns',
      building: 'the dopamine replenishment hall on the Tremor Walk',
      class: 'Anti-Parkinson; dopamine precursor (levodopa) + peripheral DOPA decarboxylase inhibitor (carbidopa)',
      mechanism: 'Levodopa crosses the BBB and is decarboxylated to dopamine by DOPA decarboxylase in surviving nigrostriatal neurons. Carbidopa inhibits peripheral DOPA decarboxylase (does not cross BBB) — reduces peripheral conversion of levodopa to dopamine, thereby: (1) increasing the proportion that reaches the brain; (2) markedly reducing peripheral dopaminergic side effects (nausea, vomiting, cardiac effects).',
      adverse_effects: 'Motor complications with long-term use: WEARING-OFF (end-of-dose deterioration — effect shortens over years); ON-OFF FLUCTUATIONS (unpredictable switches between mobility and immobility); DYSKINESIA (involuntary choreiform movements at peak dose — dose-limiting). Nausea (reduced by carbidopa). Orthostatic hypotension. Psychosis and hallucinations (dopamine excess in limbic system). Impulse control disorders.',
      clinical_use: 'Gold standard for symptomatic treatment of Parkinson\'s disease (most effective drug available). Combination with carbidopa is standard formulation. Also used in Parkinson\'s disease dementia.',
      memory_hook: 'The dopamine replenishment hall rebuilds the Tremor Walk\'s depleted pavement — but after years of rebuilding, the floor develops unpredictable hotspots (on-off fluctuations) and unwanted cracks (dyskinesias).',
      source: 'G&G 14e, ch. 21',
      high_yield: true,
    },
    {
      id: 'pramipexole',
      district: 'cns',
      building: 'the D3-preferring gambling den on the Tremor Walk',
      class: 'Anti-Parkinson; dopamine D2/D3 receptor agonist (non-ergot)',
      mechanism: 'Direct agonist at D2 and D3 dopamine receptors (D3 preference). Acts on striatal dopamine receptors independently of remaining nigrostriatal neurons (important as disease progresses). Does not require conversion to active form. Half-life ~8–12 hours. Renally excreted.',
      adverse_effects: 'IMPULSE CONTROL DISORDERS (ICD): pathological gambling, hypersexuality, compulsive shopping, binge eating — driven by D3 agonism in the mesolimbic reward circuit; patients and families must be warned. Nausea; orthostatic hypotension; somnolence; sudden sleep attacks while driving (narcolepsy-like). Pedal oedema. Dyskinesia (less than levodopa). Hallucinations. Augmentation in restless legs syndrome (worsening with dose escalation).',
      clinical_use: 'Parkinson\'s disease (early monotherapy to delay levodopa; adjunct to levodopa later); restless legs syndrome (RLS).',
      memory_hook: 'The D3-preferring gambling den on the Tremor Walk is named for the impulse control disorder — the reward-circuit D3 agonism can turn mild Parkinson\'s patients into pathological gamblers without warning.',
      source: 'G&G 14e, ch. 21',
      high_yield: true,
    },
    {
      id: 'selegiline',
      district: 'cns',
      building: 'the MAO-B inhibitor sentry post at the Tremor Walk entrance',
      class: 'Anti-Parkinson; selective MAO-B inhibitor (irreversible)',
      mechanism: 'Irreversibly and selectively inhibits MAO-B at clinical doses — MAO-B is the primary isoform that metabolises dopamine in the striatum. Reduces dopamine breakdown → prolongs dopamine effect (augments levodopa). Weak MAOI (MAO-A is not significantly inhibited at standard doses → tyramine reaction risk is low at normal doses, but increases at higher doses). Metabolised to amphetamine and methamphetamine metabolites.',
      adverse_effects: 'Nausea; insomnia (especially if taken in the afternoon — amphetamine metabolites); orthostatic hypotension. SEROTONIN SYNDROME if combined with meperidine (CONTRAINDICATED), tramadol, or SSRIs/SNRIs (use caution). At high doses, MAO-A is also inhibited → tyramine reaction risk increases.',
      clinical_use: 'Parkinson\'s disease: as adjunct to levodopa (reduces wearing-off); early monotherapy to potentially slow disease progression (neuroprotective hypothesis — debated). Transdermal form approved for MDD.',
      memory_hook: 'The MAO-B sentry blocks only the dopamine-degrading gate — at standard doses the tyramine-reaction door (MAO-A) stays open, but combined with meperidine the sentry fires dangerously: serotonin syndrome.',
      source: 'G&G 14e, ch. 21',
      high_yield: true,
    },
    {
      id: 'entacapone',
      district: 'cns',
      building: 'the COMT-inhibitor relay post along the Tremor Walk',
      class: 'Anti-Parkinson; peripheral COMT inhibitor',
      mechanism: 'Inhibits catechol-O-methyltransferase (COMT) in the periphery, blocking the methylation of levodopa to 3-O-methyldopa. This reduces peripheral levodopa degradation, increasing its bioavailability and prolonging its plasma half-life → smooths the pharmacokinetics of levodopa → reduces wearing-off. Always given WITH levodopa/carbidopa (no benefit as monotherapy). Does not significantly cross BBB (peripheral COMT inhibitor).',
      adverse_effects: 'ORANGE-BROWN URINE/STOOLS (harmless metabolite — warn patients). Nausea; diarrhoea (can be severe — may require dose reduction); dyskinesia (increased dopaminergic effect — reduce levodopa dose if occurs); orthostatic hypotension. CONTRAINDICATED with non-selective MAOIs.',
      clinical_use: 'Adjunct to levodopa/carbidopa in Parkinson\'s disease with end-of-dose wearing-off; used in fixed-dose combination formulation.',
      memory_hook: 'The COMT relay post at the Tremor Walk extends levodopa\'s journey time by blocking the methylation shortcut — the orange urine is the harmless signpost that the relay is working.',
      source: 'G&G 14e, ch. 21',
      high_yield: true,
    },
    {
      id: 'benztropine',
      district: 'cns',
      building: 'the anticholinergic tremor-rest house on the Tremor Walk',
      class: 'Anti-Parkinson; centrally-acting muscarinic antagonist (tertiary amine)',
      mechanism: 'Competitive antagonist at muscarinic receptors in the corpus striatum — blocks the relative cholinergic excess that occurs in Parkinson\'s disease when dopamine is depleted (normal balance = dopaminergic inhibition vs. cholinergic excitation of striatal output). Reduces tremor and rigidity but has less effect on bradykinesia (which is primarily dopaminergic).',
      adverse_effects: 'Anticholinergic: dry mouth; constipation; urinary retention; blurred vision; tachycardia; CONFUSION AND MEMORY IMPAIRMENT (especially in elderly — avoid in patients > 70 years or with dementia). Contraindicated in closed-angle glaucoma and prostatic hypertrophy.',
      clinical_use: 'Parkinson\'s disease: particularly useful for TREMOR-DOMINANT disease in YOUNGER patients (avoid in elderly). Acute drug-induced dystonia (e.g., from antipsychotics — IV or IM benztropine is first-line reversal agent). Drug-induced parkinsonism from antipsychotics.',
      memory_hook: 'The anticholinergic tremor-rest house quiets the cholinergic overbalance in young patients — but the elderly patient confused on the Tremor Walk is a warning sign that the anticholinergic toll is too high for old minds.',
      source: 'G&G 14e, ch. 21',
      high_yield: true,
    },

    // ─── ANAESTHETICS (ch. 22–23) ────────────────────────────────────────────

    {
      id: 'propofol',
      district: 'cns',
      building: 'the white emulsion induction bay of the Anaesthetic Theatre',
      class: 'IV general anaesthetic; GABA-A positive allosteric modulator (alkylphenol)',
      mechanism: 'Potentiates GABA-A receptor function (increases duration of Cl⁻ channel opening, similar to barbiturates). Rapid onset (< 1 minute) due to high lipophilicity and abundant cerebral blood flow. Ultra-short duration owing to rapid redistribution from brain to tissues and rapid hepatic metabolism. White lipid emulsion formulation supports microbial growth — strict aseptic technique required.',
      adverse_effects: 'Marked respiratory depression (apnoea on induction — airway equipment required). Profound hypotension and cardiac depression (vasodilation + negative inotropy — caution in hypovolaemia). Pain on IV injection. Does not provide analgesia. PROPOFOL INFUSION SYNDROME (PRIS): rare but POTENTIALLY FATAL complication with HIGH INFUSION RATES or PROLONGED INFUSION (> 48 hours in ICU setting) — characterised by: METABOLIC ACIDOSIS, RHABDOMYOLYSIS, hyperkalaemia, cardiac failure, renal failure; mechanism involves impairment of mitochondrial respiratory chain.',
      clinical_use: 'Induction of general anaesthesia; total intravenous anaesthesia (TIVA) maintenance; procedural sedation; ICU sedation (short-term).',
      memory_hook: 'The white emulsion induction bay opens the theatre instantly but slams the airway shut — and in the ICU at high rates the stage machinery overheats into propofol infusion syndrome: acidosis, rhabdo, cardiac failure.',
      source: 'G&G 14e, ch. 22',
      high_yield: true,
    },
    {
      id: 'ketamine',
      district: 'cns',
      building: 'the dissociative gallery at the Anaesthetic Theatre entrance',
      class: 'IV dissociative anaesthetic; non-competitive NMDA receptor antagonist',
      mechanism: 'Non-competitive (open-channel) antagonist of the NMDA glutamate receptor — blocks the ion channel when it is open. Produces DISSOCIATIVE ANAESTHESIA: cataleptic state with analgesia, amnesia, and sensory/environment dissociation while maintaining protective airway reflexes (relative to other anaesthetics). Sympathomimetic: increases heart rate and blood pressure (endogenous catecholamine release).',
      adverse_effects: 'Emergence phenomena: VIVID DREAMS, HALLUCINATIONS, delirium on recovery (incidence reduced by concurrent benzodiazepine use). INCREASES INTRACRANIAL PRESSURE (ICP) — traditionally CONTRAINDICATED in head injury (debated now; modern thinking more nuanced). INCREASES INTRAOCULAR PRESSURE — contraindicated in penetrating eye injury. Hypertension and tachycardia (caution in hypertensive patients). Hypersalivation. Laryngospasm (rare).',
      clinical_use: 'Emergency anaesthesia in haemodynamically unstable patients (hypovolaemia, trauma — sympathomimetic preserves blood pressure); procedural sedation in children; bronchospasm (bronchodilator); sub-anaesthetic doses for acute and chronic pain; treatment-resistant depression (IV racemic ketamine or intranasal esketamine).',
      memory_hook: 'The dissociative gallery separates perception from reality — ketamine provides analgesia without the haemodynamic collapse of propofol, but the vivid gallery paintings linger into recovery as hallucinations.',
      source: 'G&G 14e, ch. 22',
      high_yield: true,
    },
    {
      id: 'sevoflurane',
      district: 'cns',
      building: 'the volatile vapour chamber of the Anaesthetic Theatre',
      class: 'Volatile halogenated inhaled anaesthetic; enhances GABA-A and inhibits NMDA',
      mechanism: 'Inhaled fluorinated ether that enhances GABA-A (increases Cl⁻ conductance) and inhibits NMDA receptors — overall CNS depression. MAC (minimum alveolar concentration) = 2% in adults (lower in elderly, with nitrous oxide). Non-pungent odour makes it preferred for inhalational induction (gaseous induction in children). Rapid onset and offset due to low blood:gas partition coefficient. Metabolised to fluoride ions and compounds A/B (hexafluoroisopropanol — theoretical but not clinically significant nephrotoxicity at normal flow rates).',
      adverse_effects: 'Dose-dependent respiratory and cardiac depression. MALIGNANT HYPERTHERMIA: LIFE-THREATENING PHARMACOGENETIC EMERGENCY triggered by halogenated volatile anaesthetics (sevoflurane, isoflurane, halothane) and succinylcholine — uncontrolled Ca²⁺ release from sarcoplasmic reticulum due to RYR1 (ryanodine receptor 1) mutation → severe hyperthermia, rigidity, metabolic acidosis, hyperkalemia; TREATMENT: DANTROLENE (direct sarcoplasmic reticulum Ca²⁺ release blocker), body cooling, supportive care. Nephrotoxicity concern at very low flow rates (compound A).',
      clinical_use: 'Maintenance of general anaesthesia; inhalational induction (paediatrics); cardiac surgery (cardioprotective preconditioning).',
      memory_hook: 'The volatile vapour chamber is efficient and pleasant — but the malignant hyperthermia warning is on every door: sevoflurane plus succinylcholine in a susceptible RYR1 patient sets the furnace to lethal, and only dantrolene can close the valve.',
      source: 'G&G 14e, ch. 22',
      high_yield: true,
    },
    {
      id: 'nitrous_oxide',
      district: 'cns',
      building: 'the laughing-gas anteroom of the Anaesthetic Theatre',
      class: 'Inhaled anaesthetic (inorganic gas); NMDA antagonist, opioid receptor modulation',
      mechanism: 'NMDA receptor antagonist (primary mechanism) — reduces excitatory glutamate transmission. Has some opioid receptor activity. Very low potency (MAC = 104% — cannot achieve surgical anaesthesia as sole agent at sea level). SECOND-GAS EFFECT: when nitrous oxide is rapidly absorbed in large volumes during uptake, it concentrates co-administered vapours and increases their alveolar tension. Diffuses faster than nitrogen → DIFFUSION HYPOXIA at emergence if supplemental O₂ is not administered.',
      adverse_effects: 'INACTIVATION OF VITAMIN B12 (cobalamin): nitrous oxide irreversibly oxidises the cobalt in vitamin B12 → inhibits methionine synthase → impaired DNA synthesis and myelin production; risk of megaloblastic anaemia and SUBACUTE COMBINED DEGENERATION OF THE SPINAL CORD with prolonged or repeated exposure (also relevant in patients with pre-existing B12 deficiency — a single anaesthetic can precipitate neurological injury). DIFFUSION HYPOXIA at termination (administer 100% O₂ for several minutes). Increases gas in enclosed spaces (pneumothorax, bowel obstruction, middle ear — avoid). PONV (postoperative nausea).',
      clinical_use: 'Adjunct to general anaesthesia (reduces MAC of volatile agents by ~50%); labour analgesia (50% N₂O/50% O₂ mixture); procedural analgesia (dental, wound care).',
      memory_hook: 'The laughing-gas anteroom boosts the vapour next door via the second-gas effect — but at the end of the show, B12 has been oxidised and diffusion hypoxia sets in unless 100% oxygen is given on the way out.',
      source: 'G&G 14e, ch. 22',
      high_yield: true,
    },
    {
      id: 'lidocaine_local',
      district: 'cns',
      building: 'the amide nerve-block parlour beside the Anaesthetic Theatre',
      class: 'Amide local anaesthetic; voltage-gated Na⁺ channel blocker',
      mechanism: 'Diffuses through the nerve membrane in uncharged (lipid-soluble) form; intracellularly protonates to charged (quaternary) form, which binds and blocks voltage-gated Na⁺ channels from the intracellular side (use-dependent / frequency-dependent block — blocks more at higher firing rates). Blocks small unmyelinated C fibres (pain) at lower concentrations than large myelinated Aα motor fibres → differential sensory-motor block possible. Amide: metabolised hepatically (vs. ester local anaesthetics metabolised by plasma pseudocholinesterase).',
      adverse_effects: 'CNS toxicity (from systemic absorption or inadvertent IV injection): tinnitus, perioral numbness, dizziness → seizures; peri-arrest arrhythmias. CARDIAC: negative inotrope, prolongs conduction — NOTE: LESS CARDIOTOXIC than bupivacaine. Hypersensitivity (rare for amides — more common with esters like benzocaine). Methaemoglobinaemia (topical benzocaine > lidocaine — benzocaine especially).',
      clinical_use: 'Infiltration anaesthesia; nerve block (peripheral nerve, epidural, spinal); topical anaesthesia; IV lidocaine for perioperative analgesia and for lidocaine infusion in neuropathic pain (separate from IV antiarrhythmic use).',
      memory_hook: 'The amide nerve-block parlour closes the sodium door at the frequency of pain — C fibres fall silent before motor fibres, and lidocaine\'s cardiac window is wider than bupivacaine\'s, making it safer if blood vessels are struck.',
      source: 'G&G 14e, ch. 23',
      high_yield: true,
    },
    {
      id: 'bupivacaine',
      district: 'cns',
      building: 'the long-duration cardiac-caution suite of the Anaesthetic Theatre',
      class: 'Amide local anaesthetic; long-acting, high cardiotoxicity risk',
      mechanism: 'Same mechanism as lidocaine (Na⁺ channel block). LONGER-ACTING than lidocaine due to high protein binding (95%) and greater lipid solubility. Preferentially blocks cardiac Na⁺ channels with SLOW DISSOCIATION from inactivated state — resulting in a wider clinical concern for CARDIOTOXICITY than lidocaine: accidental intravascular injection can cause VENTRICULAR ARRHYTHMIAS AND CARDIAC ARREST that is difficult to resuscitate. Levobupivacaine and ropivacaine (S-enantiomers) have improved cardiac safety profiles.',
      adverse_effects: 'CARDIOTOXICITY: severe ventricular arrhythmias (including refractory ventricular fibrillation), cardiovascular collapse following IV injection — harder to reverse than lidocaine toxicity. CNS toxicity (seizures) from systemic absorption. Treatment of intravascular injection: INTRALIPID (20% lipid emulsion) — "lipid rescue" sequesters bupivacaine in the lipid phase.',
      clinical_use: 'Epidural anaesthesia and analgesia (labour, post-operative); spinal anaesthesia; peripheral nerve blocks; intercostal block; wound infiltration (long duration beneficial — up to 8 hours).',
      memory_hook: 'The cardiac-caution suite\'s sign reads "slow dissociation from heart Na⁺ channels" — bupivacaine is harder to dislodge from myocardial sodium channels than lidocaine, so a misplaced injection means a resuscitation fight that lipid rescue may just barely win.',
      source: 'G&G 14e, ch. 23',
      high_yield: true,
    },

    // ─── OPIOIDS (ch. 20) ────────────────────────────────────────────────────

    {
      id: 'morphine',
      district: 'cns',
      building: 'the original opium archive at the heart of the Opium Den',
      class: 'Opioid agonist; full mu (μ) receptor agonist — prototype',
      mechanism: 'Full agonist at mu opioid receptors (MOR, OPRM1) — couples to Gi/o protein: reduces adenylyl cyclase activity (↓cAMP), opens K⁺ channels (hyperpolarisation), closes voltage-gated Ca²⁺ channels. Net effect: decreased neuronal excitability and reduced neurotransmitter release. Analgesic effects via supraspinal (PAG, rostral ventromedial medulla), spinal (dorsal horn), and peripheral sites. Active metabolite morphine-6-glucuronide (M6G) has opioid agonist activity — accumulates in renal failure.',
      adverse_effects: 'RESPIRATORY DEPRESSION (most dangerous — dose-dependent; reduced hypercapnic drive); CONSTIPATION (via enteric mu receptors — tolerance does not develop to this effect); MIOSIS (pupillary constriction, even in overdose); nausea and vomiting (CTZ); urinary retention; sedation; physical dependence; histamine release (itching, hypotension — especially IV morphine); ITCHING (particularly intrathecal morphine). OVERDOSE TRIAD: COMA + MIOSIS + RESPIRATORY DEPRESSION.',
      clinical_use: 'Moderate-to-severe acute and chronic pain; acute pulmonary oedema (reduces preload via venodilation); STEMI pain; dyspnoea in palliative care; post-operative analgesia.',
      memory_hook: 'The original opium archive holds the three keys to the overdose vault: coma, miosis, respiratory depression — morphine\'s triad that naloxone unlocks.',
      source: 'G&G 14e, ch. 20',
      high_yield: true,
    },
    {
      id: 'fentanyl',
      district: 'cns',
      building: 'the high-potency vault deep in the Opium Den',
      class: 'Opioid agonist; highly lipophilic synthetic mu agonist',
      mechanism: 'Full mu receptor agonist; 80–100× more potent than morphine. Highly lipophilic → rapid onset (seconds IV) and rapid brain penetration. SHORT duration IV due to rapid redistribution to fat and muscle. Transdermal patch provides prolonged delivery (12–24 hour absorption lag; reservoir in skin). Metabolised by CYP3A4 to inactive norfentanyl.',
      adverse_effects: 'CHEST WALL RIGIDITY ("wooden chest syndrome"): at high IV doses — rigidity of respiratory muscles may cause inability to ventilate; treat with neuromuscular blockade and naloxone. Respiratory depression. Bradycardia. Profound sedation. Constipation. Itching. No histamine release (advantage over morphine). TOLERANCE AND DEPENDENCE. Transdermal patch: delayed toxicity — if patch removed after adverse effects, residual skin depot continues absorption.',
      clinical_use: 'IV anaesthesia and perioperative analgesia; procedural sedation (IV); intrathecal and epidural analgesia; transdermal patch for chronic cancer and non-cancer pain; intranasal and buccal formulations for breakthrough cancer pain.',
      memory_hook: 'The high-potency vault strikes 100 times harder than morphine\'s archive — the wooden chest sign is fentanyl\'s signature overdose: too rigid to breathe, paralysis needed before naloxone can clear the airways.',
      source: 'G&G 14e, ch. 20',
      high_yield: true,
    },
    {
      id: 'tramadol',
      district: 'cns',
      building: 'the dual-mechanism crossroads of the Opium Den',
      class: 'Weak opioid agonist + SNRI; centrally-acting analgesic',
      mechanism: 'TWO MECHANISMS: (1) weak mu opioid receptor agonism (active metabolite O-desmethyltramadol [M1] has higher mu affinity — metabolised by CYP2D6; poor CYP2D6 metabolisers have reduced efficacy); (2) inhibits reuptake of serotonin and norepinephrine (SNRI-like). Lower respiratory depression risk than morphine at equianalgesic doses, but respiratory depression still occurs in overdose.',
      adverse_effects: 'Nausea; vomiting; dizziness; constipation; SEIZURES (lowers seizure threshold — especially in overdose and in combination with SSRIs; CONTRAINDICATED in epilepsy or with drugs that lower seizure threshold). SEROTONIN SYNDROME in combination with SSRIs, SNRIs, MAOIs, or other serotonergic drugs — potentially fatal; MAOI + tramadol is CONTRAINDICATED. Physical dependence and withdrawal.',
      clinical_use: 'Moderate pain (particularly musculoskeletal and neuropathic components). NOT first-line for severe pain. Avoid in patients on MAOIs or SSRIs.',
      memory_hook: 'The dual-mechanism crossroads carries two flags: opioid and SNRI — the SNRI flag means SSRIs and MAOIs approach at the crossroads at their peril, since serotonin syndrome can kill at the intersection.',
      source: 'G&G 14e, ch. 20',
      high_yield: true,
    },
    {
      id: 'methadone',
      district: 'cns',
      building: 'the QT-monitored long-stay lodge of the Opium Den',
      class: 'Full mu opioid agonist (long-acting) + NMDA receptor antagonist',
      mechanism: 'Full mu agonist; also NMDA receptor antagonist (contributes to efficacy in neuropathic pain and opioid tolerance). Very long and VARIABLE half-life (24–36 hours, range 8–80 hours) — accumulation risk. QTc PROLONGATION via hERG K⁺ channel block — risk of torsades de pointes, especially at higher doses and with other QTc-prolonging agents. No active metabolites. Hepatic metabolism via CYP3A4 and CYP2D6 (many drug interactions).',
      adverse_effects: 'PROLONGED QTc AND TORSADES DE POINTES (MANDATORY ECG MONITORING, especially when initiating or dose-escalating). Respiratory depression (long half-life makes accumulation and delayed toxicity a concern). Constipation. Sedation. Diaphoresis. Physical dependence.',
      clinical_use: 'OPIOID USE DISORDER maintenance treatment (reduces cravings and withdrawal; administered as supervised oral daily dose from licensed clinic). Severe chronic pain (cancer and non-cancer); neuropathic pain (NMDA antagonism). Detoxification from heroin and other opioids.',
      memory_hook: 'The QT-monitored long-stay lodge keeps residents stable — but the mandatory ECG monitor above every bed reminds prescribers that methadone prolongs QTc and the torsades lurk in the long-half-life accumulation.',
      source: 'G&G 14e, ch. 20',
      high_yield: true,
    },
    {
      id: 'buprenorphine',
      district: 'cns',
      building: 'the partial-agonist clinic at the border of the Opium Den',
      class: 'Partial mu opioid agonist + kappa antagonist (opioid partial agonist)',
      mechanism: 'PARTIAL AGONIST at mu opioid receptors — high receptor affinity but PARTIAL intrinsic activity: CEILING EFFECT for respiratory depression at high doses (improved safety profile over full agonists). Very high receptor affinity displaces full agonists (can precipitate withdrawal if given to a patient physically dependent on a full agonist — timing matters). Long half-life (24–72 hours). Sublingual (SL) formulation avoids extensive first-pass; combined with naloxone (SL naloxone inactive → absorbed if injected → precipitates withdrawal — deters IV misuse).',
      adverse_effects: 'Nausea; constipation; sedation; headache. PRECIPITATED WITHDRAWAL if given to full-agonist-dependent patient without adequate washout (must wait until early withdrawal symptoms appear — COWS ≥8 before dosing). Hepatotoxicity (rarely, at high doses). Respiratory depression still possible (partial agonist — ceiling does not eliminate risk in naive patients or with CNS depressants).',
      clinical_use: 'OPIOID USE DISORDER (OUD) — first-line (usually as buprenorphine/naloxone combination); moderate-to-severe chronic pain (patch formulation); acute pain (IV formulation).',
      memory_hook: 'The partial-agonist clinic fills the mu receptor only halfway — the ceiling on respiratory depression makes it safer than full agonists, but the receptor affinity is so high it will oust morphine and trigger withdrawal if the patient still has full agonist on board.',
      source: 'G&G 14e, ch. 20',
      high_yield: true,
    },
    {
      id: 'naloxone',
      district: 'cns',
      building: 'the emergency reversal station at the Opium Den exit',
      class: 'Pure opioid antagonist; competitive, all receptor subtypes',
      mechanism: 'Competitive antagonist at mu, kappa, and delta opioid receptors with no intrinsic opioid agonist activity. Very high affinity displaces opioid agonists from receptors. SHORT half-life (30–80 minutes) — much shorter than most opioids it reverses, so RE-NARCOTIZATION can occur when naloxone is metabolised before the opioid is cleared (may require repeat dosing or infusion). IV form: rapid onset (2 minutes). Intranasal formulation available for community overdose reversal.',
      adverse_effects: 'PRECIPITATED OPIOID WITHDRAWAL in opioid-dependent patients: tachycardia, hypertension, agitation, vomiting, pulmonary oedema (potentially fatal — titrate carefully; use minimum effective dose). Titration key: restore respiratory rate without triggering severe withdrawal.',
      clinical_use: 'OPIOID OVERDOSE REVERSAL (IV, IM, IN, SC); postoperative opioid excess; diagnosis of suspected opioid dependence (precipitates withdrawal rapidly); component of buprenorphine/naloxone combination formulation (sublingual naloxone inactive).',
      memory_hook: 'The emergency reversal station throws open the mu door and pushes morphine out — but naloxone\'s shift ends in less than an hour, so the patient must be watched for re-narcotization long after the station\'s lights go out.',
      source: 'G&G 14e, ch. 20',
      high_yield: true,
    },

  ],
};

if (typeof window !== 'undefined') window.DISTRICT_CNS = DISTRICT_CNS;
