const DISTRICT_ENDOCRINE = {
  id: 'endocrine',
  name: 'Endocrine',
  theme_line: 'Glandular heights · hormones above the city',
  walkthrough: `The Endocrine plateau rises above the rest of the city, white-marble glands arrayed like temples catching the thin air. The pituitary sits at the summit — a twin-lobed cupola that controls the entire hillside with slow, pulsed dispatches. Below it, on a limestone terrace, the thyroid temple and four tiny parathyroid shrines are carved into the cliff face; next comes the adrenal courtyard, its outer cortex colonnade wrapping three tiers — mineralocorticoid, glucocorticoid, sex-steroid — and its inner medulla sunk in shadow. Further down the slope, the gonadal pavilions open onto a sunny esplanade of sex-hormone merchants, contraceptive booths, and aromatase foundries. At the foot of the hill, the pancreatic islets lie sunken into a sweet-smelling courtyard tiled in pale blue: beta-cell vendors selling insulin in every formulation, alpha-cell bakers peddling glucagon, and a row of newer stalls — DPP-4 inhibitor kiosks, GLP-1 RA juice bars, SGLT2 kidney-sluice shops — jostling for space around the ancient metformin mill.

Hormonal couriers move along covered colonnades — the endocrine signals are slow and powerful, not the lightning of the adrenergic plant nor the chemistry-class rush of the autacoid messenger lane. Each courier carries a lipid or peptide envelope that must be decoded at the receptor before the message inside can act. To learn this district is to trace the colonnades: follow the pituitary dispatch down to the thyroid, the adrenal relay back up to the cortex, the insulin signal from islet to liver. Every therapeutic intervention on this plateau is either a hormone you are replacing, an enzyme you are blocking, or a receptor you are nudging — and every drug here can become dangerous the moment you abruptly cut the courier line.`,
  palette: { ground: 0xE8D5A3, accent: 0xC47E3A, water: 0x7BAFD4 },
  position: { x: 40, z: -40 },
  classification: {
    sources: [
      {
        label: 'G&G 14e',
        cite: 'ch. 45–52',
        groups: [
          { heading: 'A. Antidiabetic drugs', groups: [
            { heading: 'Insulins', groups: [
              { heading: 'Rapid-acting', drugs: ['Insulin lispro', 'Insulin aspart', 'Insulin glulisine'] },
              { heading: 'Short-acting (regular)', drugs: ['Regular insulin'] },
              { heading: 'Intermediate-acting', drugs: ['NPH (isophane) insulin'] },
              { heading: 'Long-acting', drugs: ['Insulin glargine', 'Insulin detemir', 'Insulin degludec'] },
            ]},
            { heading: 'Biguanides', drugs: ['Metformin'] },
            { heading: 'Sulfonylureas', drugs: ['Glibenclamide', 'Glimepiride', 'Gliclazide'] },
            { heading: 'Meglitinides', drugs: ['Repaglinide', 'Nateglinide'] },
            { heading: 'Thiazolidinediones', drugs: ['Pioglitazone'] },
            { heading: 'DPP-4 inhibitors (gliptins)', drugs: ['Sitagliptin', 'Vildagliptin', 'Linagliptin'] },
            { heading: 'GLP-1 receptor agonists', drugs: ['Liraglutide', 'Exenatide', 'Dulaglutide', 'Semaglutide'] },
            { heading: 'Dual GIP/GLP-1 receptor agonist', drugs: ['Tirzepatide'] },
            { heading: 'SGLT2 inhibitors (gliflozins)', drugs: ['Empagliflozin', 'Dapagliflozin', 'Canagliflozin'] },
            { heading: 'α-glucosidase inhibitors', drugs: ['Acarbose', 'Miglitol', 'Voglibose'] },
            { heading: 'Amylin analogue', drugs: ['Pramlintide'] },
          ]},
          { heading: 'B. Thyroid & antithyroid drugs', groups: [
            { heading: 'Thyroid hormones', drugs: ['Levothyroxine', 'Liothyronine'] },
            { heading: 'Antithyroid drugs', groups: [
              { heading: 'Thioamides', drugs: ['Carbimazole', 'Methimazole', 'Propylthiouracil'] },
              { heading: 'Iodides', drugs: ['Potassium iodide', 'Lugol\'s iodine'] },
              { heading: 'Radioactive iodine', drugs: ['I-131'] },
              { heading: 'β-blockers (symptomatic)', drugs: ['Propranolol'] },
            ]},
          ]},
          { heading: 'C. Corticosteroids', groups: [
            { heading: 'Glucocorticoids', groups: [
              { heading: 'Short-acting', drugs: ['Hydrocortisone', 'Cortisone'] },
              { heading: 'Intermediate-acting', drugs: ['Prednisolone', 'Methylprednisolone', 'Triamcinolone', 'Deflazacort'] },
              { heading: 'Long-acting', drugs: ['Dexamethasone', 'Betamethasone'] },
            ]},
            { heading: 'Mineralocorticoids', drugs: ['Fludrocortisone'] },
          ]},
          { heading: 'D. Sex hormones & related drugs', groups: [
            { heading: 'Estrogens & progestins', drugs: ['Combined oral contraceptives', 'Estradiol', 'Progesterone', 'Medroxyprogesterone'] },
            { heading: 'SERMs', drugs: ['Tamoxifen', 'Raloxifene', 'Clomiphene'] },
            { heading: 'Aromatase inhibitors', drugs: ['Anastrozole', 'Letrozole', 'Exemestane'] },
            { heading: 'Androgens & anti-androgens', drugs: ['Testosterone', 'Finasteride', 'Dutasteride', 'Flutamide', 'Bicalutamide', 'Leuprolide (GnRH agonist)', 'Goserelin'] },
            { heading: 'Antiprogestin', drugs: ['Mifepristone'] },
            { heading: 'Impeded androgen', drugs: ['Danazol'] },
          ]},
          { heading: 'E. Drugs affecting bone & calcium', groups: [
            { heading: 'Bisphosphonates', drugs: ['Alendronate', 'Zoledronic acid', 'Risedronate', 'Ibandronate'] },
            { heading: 'RANKL inhibitor', drugs: ['Denosumab'] },
            { heading: 'Sclerostin inhibitor', drugs: ['Romosozumab'] },
            { heading: 'PTH analogue', drugs: ['Teriparatide', 'Abaloparatide'] },
            { heading: 'SERM', drugs: ['Raloxifene'] },
            { heading: 'Calcitonin', drugs: ['Calcitonin'] },
            { heading: 'Vitamin D & calcium', drugs: ['Vitamin D', 'Calcium'] },
          ]},
          { heading: 'F. Hypothalamic & pituitary hormones', groups: [
            { heading: 'Posterior pituitary', drugs: ['Desmopressin (vasopressin)', 'Terlipressin', 'Oxytocin'] },
            { heading: 'Somatostatin analogue', drugs: ['Octreotide', 'Lanreotide'] },
            { heading: 'Growth hormone', drugs: ['Somatropin'] },
            { heading: 'Dopamine agonists', drugs: ['Bromocriptine', 'Cabergoline'] },
          ]},
        ],
      },
      {
        label: 'KDT 8e/9e',
        cite: 'ch. 18–24, 62–63',
        groups: [
          { heading: 'A. Antidiabetic drugs', groups: [
            { heading: 'Insulins', groups: [
              { heading: 'Rapid-acting', drugs: ['Insulin lispro', 'Insulin aspart', 'Insulin glulisine'] },
              { heading: 'Short-acting (regular)', drugs: ['Regular (soluble) insulin'] },
              { heading: 'Intermediate-acting', drugs: ['NPH (isophane) insulin'] },
              { heading: 'Long-acting', drugs: ['Insulin glargine', 'Insulin detemir', 'Insulin degludec'] },
            ]},
            { heading: 'Biguanides', drugs: ['Metformin'] },
            { heading: 'Sulfonylureas', drugs: ['Glibenclamide', 'Glimepiride', 'Gliclazide'] },
            { heading: 'Meglitinides / D-phenylalanine analogue', drugs: ['Repaglinide', 'Nateglinide'] },
            { heading: 'Thiazolidinediones (PPARγ activators)', drugs: ['Pioglitazone'] },
            { heading: 'DPP-4 inhibitors (gliptins)', drugs: ['Sitagliptin', 'Vildagliptin', 'Linagliptin'] },
            { heading: 'GLP-1 receptor agonists (incretin mimetics)', drugs: ['Liraglutide', 'Exenatide', 'Dulaglutide', 'Semaglutide'] },
            { heading: 'Dual GIP/GLP-1 receptor agonist', drugs: ['Tirzepatide'] },
            { heading: 'SGLT2 inhibitors (gliflozins)', drugs: ['Empagliflozin', 'Dapagliflozin', 'Canagliflozin'] },
            { heading: 'α-glucosidase inhibitors', drugs: ['Acarbose', 'Miglitol', 'Voglibose'] },
            { heading: 'Amylin analogue', drugs: ['Pramlintide'] },
          ]},
          { heading: 'B. Thyroid & antithyroid drugs', groups: [
            { heading: 'Thyroid hormones', drugs: ['Levothyroxine (T4)', 'Liothyronine (T3)'] },
            { heading: 'Antithyroid drugs', groups: [
              { heading: 'Thioamides (inhibit hormone synthesis)', drugs: ['Carbimazole', 'Methimazole', 'Propylthiouracil'] },
              { heading: 'Ionic inhibitors / iodides', drugs: ['Potassium iodide', 'Lugol\'s iodine'] },
              { heading: 'Radioactive iodine', drugs: ['I-131'] },
              { heading: 'β-adrenergic blockers (symptomatic relief)', drugs: ['Propranolol'] },
            ]},
          ]},
          { heading: 'C. Corticosteroids', groups: [
            { heading: 'Glucocorticoids', groups: [
              { heading: 'Short-acting', drugs: ['Hydrocortisone', 'Cortisone'] },
              { heading: 'Intermediate-acting', drugs: ['Prednisolone', 'Methylprednisolone', 'Triamcinolone', 'Deflazacort'] },
              { heading: 'Long-acting', drugs: ['Dexamethasone', 'Betamethasone'] },
            ]},
            { heading: 'Mineralocorticoids', drugs: ['Fludrocortisone', 'Desoxycorticosterone'] },
          ]},
          { heading: 'D. Sex hormones & related drugs', groups: [
            { heading: 'Estrogens & progestins', drugs: ['Combined oral contraceptives', 'Estradiol', 'Progesterone', 'Medroxyprogesterone'] },
            { heading: 'SERMs (anti-estrogens)', drugs: ['Tamoxifen', 'Raloxifene', 'Clomiphene'] },
            { heading: 'Aromatase inhibitors', drugs: ['Anastrozole', 'Letrozole', 'Exemestane'] },
            { heading: 'Androgens & anti-androgens', drugs: ['Testosterone', 'Finasteride', 'Dutasteride', 'Flutamide', 'Bicalutamide', 'Leuprolide (GnRH agonist)', 'Goserelin'] },
            { heading: 'Antiprogestin', drugs: ['Mifepristone'] },
            { heading: 'Impeded androgen', drugs: ['Danazol'] },
          ]},
          { heading: 'E. Drugs affecting bone mineral homeostasis (calcium)', groups: [
            { heading: 'Bisphosphonates', drugs: ['Alendronate', 'Zoledronic acid', 'Risedronate', 'Ibandronate'] },
            { heading: 'RANKL inhibitor', drugs: ['Denosumab'] },
            { heading: 'Sclerostin inhibitor', drugs: ['Romosozumab'] },
            { heading: 'PTH (teriparatide) analogue', drugs: ['Teriparatide', 'Abaloparatide'] },
            { heading: 'SERM', drugs: ['Raloxifene'] },
            { heading: 'Calcitonin', drugs: ['Calcitonin'] },
            { heading: 'Vitamin D & calcium salts', drugs: ['Vitamin D', 'Calcium'] },
          ]},
          { heading: 'F. Hypothalamic & pituitary hormones', groups: [
            { heading: 'Posterior pituitary hormones', drugs: ['Desmopressin (vasopressin)', 'Terlipressin', 'Oxytocin'] },
            { heading: 'Somatostatin analogue', drugs: ['Octreotide', 'Lanreotide'] },
            { heading: 'Growth hormone', drugs: ['Somatropin'] },
            { heading: 'Dopamine agonists (prolactin inhibitors)', drugs: ['Bromocriptine', 'Cabergoline'] },
          ]},
        ],
      },
    ],
  },
  drugs: [

    // ─── DIABETES: INSULIN ────────────────────────────────────────────────────

    {
      id: 'insulin_regular',
      district: 'endocrine',
      building: 'the central clear-glass insulin depot at the heart of the islet courtyard',
      class: 'Short-acting human insulin; pancreatic hormone replacement',
      mechanism: 'Binds the insulin receptor (tyrosine kinase) on muscle, adipose, and hepatic cells, activating the PI3K–Akt pathway. Stimulates GLUT4 translocation to the cell surface (muscle and fat), promotes glycogen synthesis, inhibits gluconeogenesis and lipolysis, and drives potassium into cells via Na/K-ATPase stimulation. Regular insulin is the unmodified human sequence and can be given IV (the only insulin suitable for IV infusion).',
      adverse_effects: 'Hypoglycaemia (most important; confusion, sweating, tachycardia, coma at severe levels); hypokalaemia; lipohypertrophy at injection sites; weight gain; hypersensitivity reactions (rare with human insulin).',
      clinical_use: 'IV infusion in DKA, hyperglycaemic hyperosmolar state, perioperative glycaemic control, and hyperkalaemia (drives K⁺ intracellularly). SC injection for meal-time insulin coverage. Sliding-scale regimens in hospital.',
      memory_hook: 'The clear-glass depot is the only one with a river entrance — regular insulin is the only one that flows intravenously, straight into the blood without depot delay.',
      source: 'G&G 14e, ch. 51',
      high_yield: true,
    },
    {
      id: 'insulin_glargine',
      district: 'endocrine',
      building: 'the slow-burn night-watch tower on the eastern wall of the islet courtyard',
      class: 'Long-acting basal insulin analogue (once-daily)',
      mechanism: 'Insulin glargine has two extra arginine residues and a Gly-to-Ala substitution at position 21 of the A-chain, shifting its isoelectric point to physiological pH. After SC injection, it precipitates and forms a depot that dissolves slowly, releasing insulin at a nearly peakless rate over approximately 24 hours. Same receptor mechanism as regular insulin.',
      adverse_effects: 'Hypoglycaemia (less frequent nocturnal hypoglycaemia than NPH); weight gain; lipohypertrophy; cannot be mixed with other insulins in the same syringe (pH incompatibility).',
      clinical_use: 'Once-daily basal insulin in type 1 and type 2 diabetes. Provides stable background suppression of hepatic glucose output; requires a rapid-acting insulin at meals for full coverage.',
      memory_hook: 'The night-watch tower burns low and steady from dusk to dawn — no spike, no dip, just a peakless guard of basal glucose suppression through the long hours.',
      source: 'G&G 14e, ch. 51',
      high_yield: true,
    },
    {
      id: 'insulin_lispro',
      district: 'endocrine',
      building: 'the rapid-dispatch mealtime kiosk with the reversed-sign at the courtyard entrance',
      class: 'Rapid-acting insulin analogue (mealtime bolus)',
      mechanism: 'Pro→Lys and Lys→Pro swap at positions B28–B29 prevents dimerisation/hexamerisation in the SC depot, enabling monomeric rapid absorption (onset ~15 min). Binds the insulin receptor identically to regular insulin. Peak within 60 min and duration ~3–4 hours closely matches postprandial glucose excursion.',
      adverse_effects: 'Hypoglycaemia if injection is not followed immediately by a carbohydrate meal; weight gain; injection site reactions.',
      clinical_use: 'Mealtime bolus insulin in T1DM and T2DM. Can also be used in insulin pump infusion. Given immediately before or just after eating. insulin_aspart has an essentially equivalent profile.',
      memory_hook: 'The reversed-sign (Lys-Pro instead of Pro-Lys) means the hexamer refuses to form, so the courier dashes off the moment the needle clicks — fastest delivery in the courtyard.',
      source: 'G&G 14e, ch. 51',
      high_yield: true,
    },

    // ─── DIABETES: ORAL / INJECTABLE NON-INSULIN ──────────────────────────────

    {
      id: 'metformin',
      district: 'endocrine',
      building: 'the ancient biguanide mill beside the courtyard river gate',
      class: 'Biguanide; first-line oral antidiabetic',
      mechanism: 'Activates AMP-activated protein kinase (AMPK) through complex I inhibition in hepatic mitochondria → suppresses hepatic gluconeogenesis (primary mechanism). Also enhances peripheral insulin sensitivity and slows intestinal glucose absorption. Does not stimulate insulin secretion — no intrinsic hypoglycaemia risk. Also reduces LDL. Mechanism of AMPK activation is partially via LKB1 kinase.',
      adverse_effects: 'GI symptoms (nausea, diarrhoea, metallic taste) — improve with food or extended-release formulation; vitamin B12 malabsorption with long-term use; lactic acidosis (rare but potentially fatal — risk amplified in renal impairment, hepatic failure, congestive heart failure, sepsis, excessive alcohol). MUST BE WITHHELD before iodinated contrast administration and in acute kidney injury owing to lactic acidosis risk.',
      clinical_use: 'First-line for type 2 diabetes (unless contraindicated by renal/hepatic impairment or contrast procedure). Reduces macrovascular outcomes (UKPDS). Safe in combination with any other antidiabetic. Also used off-label in PCOS for insulin sensitisation.',
      memory_hook: 'The mill grinds hepatic glucose production to a halt at the AMPK wheel — but the river gate must close when contrast dye or kidney injury threatens, or the lactic acid backs up into the millpond.',
      source: 'G&G 14e, ch. 51',
      high_yield: true,
    },
    {
      id: 'glibenclamide',
      district: 'endocrine',
      building: 'the KATP-closure sluice house at the beta-cell tier of the islet courtyard',
      class: 'Sulfonylurea (second generation); insulin secretagogue',
      mechanism: 'Binds the SUR1 subunit of the pancreatic KATP channel on beta cells, closing the channel. K⁺ remains inside → cell membrane depolarises → L-type voltage-gated Ca²⁺ channels open → intracellular Ca²⁺ rise triggers exocytosis of insulin-containing granules. Acts independently of blood glucose level, so insulin is secreted even in the fasting state.',
      adverse_effects: 'Hypoglycaemia (most important and dangerous ADR; prolonged and severe especially with glibenclamide, in elderly, CKD, skipped meals; fatalities reported with long-acting agents); weight gain (insulin secretion promotes anabolism); hyponatraemia (ADH-potentiating effect); drug interactions via CYP2C9.',
      clinical_use: 'Type 2 diabetes when lifestyle and metformin are insufficient. Avoid or use with extreme caution in elderly and patients with renal impairment owing to risk of severe prolonged hypoglycaemia. Gliclazide (modified-release) has a shorter half-life and lower hypoglycaemia risk in renal impairment compared with glibenclamide.',
      memory_hook: 'The sluice house slams the KATP gates shut regardless of how full the river is — insulin pours out even on a fasting morning, and an elderly villager downstream can drown in the flood.',
      source: 'G&G 14e, ch. 51',
      high_yield: true,
    },
    {
      id: 'pioglitazone',
      district: 'endocrine',
      building: 'the PPAR-γ nucleus pavilion at the adipose terrace of the islet district',
      class: 'Thiazolidinedione (glitazone); PPAR-γ agonist; insulin sensitiser',
      mechanism: 'Activates peroxisome-proliferator-activated receptor gamma (PPAR-γ), a nuclear receptor that regulates transcription of genes involved in glucose and lipid homeostasis. Increases insulin sensitivity in adipose tissue, skeletal muscle, and liver; promotes differentiation of small, insulin-sensitive adipocytes; reduces free fatty acid flux; lowers insulin resistance without directly stimulating insulin secretion.',
      adverse_effects: 'Fluid retention and peripheral oedema (sodium retention via collecting duct PPAR-γ); CONTRAINDICATED in heart failure NYHA class III–IV (fluid retention exacerbates HF); weight gain; hepatotoxicity (troglitazone withdrawn for this — pioglitazone has a low but real signal); bladder cancer signal (pioglitazone specifically — caution in patients with haematuria or prior bladder cancer); bone loss / increased fracture risk in women; LDL-lowering effect but HDL-raising (metabolically mixed).',
      clinical_use: 'Type 2 diabetes as second-line or add-on therapy. Beneficial in NASH (fatty liver disease). Avoid in oedematous states, cardiac failure, and patients at risk of bladder cancer.',
      memory_hook: 'The PPAR nucleus pavilion rewrites the fat cells\' architecture — the insulin resistance crumbles, but the pavilion floods during rain (oedema, HF) and leaves a suspicious stain on the bladder tile.',
      source: 'G&G 14e, ch. 51',
      high_yield: true,
    },
    {
      id: 'sitagliptin',
      district: 'endocrine',
      building: 'the DPP-4 scissor-gate checkpoint at the GLP-1 messenger lane',
      class: 'DPP-4 inhibitor (gliptin); incretin enhancer',
      mechanism: 'Inhibits dipeptidyl peptidase-4, the enzyme that rapidly degrades endogenous GLP-1 and GIP after meal-stimulated secretion. By preventing GLP-1 inactivation, sitagliptin prolongs and enhances incretin-mediated: (1) glucose-dependent insulin secretion from beta cells, (2) suppression of glucagon from alpha cells, and (3) delayed gastric emptying. Glucose-dependent mechanism means minimal hypoglycaemia risk in monotherapy.',
      adverse_effects: 'Nasopharyngitis; urinary tract infections; rare reports of acute pancreatitis (class effect — monitor for abdominal pain); rare severe arthralgia (joint pain); possible increased risk of heart failure hospitalisation with saxagliptin (class effect concern, though sitagliptin neutral in TECOS trial).',
      clinical_use: 'Type 2 diabetes as add-on to metformin or other agents. Good tolerability; weight-neutral; safe in the elderly (dose-reduce in CKD). Not associated with cardiovascular mortality benefit.',
      memory_hook: 'The scissor gate is padlocked — DPP-4 can no longer cut the GLP-1 messenger before it finishes its glucose-dependent errand, so the beta cell hears the full signal.',
      source: 'G&G 14e, ch. 51',
      high_yield: true,
    },
    {
      id: 'liraglutide',
      district: 'endocrine',
      building: 'the GLP-1 receptor juice bar on the western promenade of the islet courtyard',
      class: 'GLP-1 receptor agonist; incretin mimetic (long-acting)',
      mechanism: 'Fatty-acid–acylated GLP-1 analogue that binds and activates the GLP-1 receptor with high affinity. Stimulates glucose-dependent insulin secretion, suppresses glucagon, slows gastric emptying, and activates hypothalamic satiety centres (weight loss). Once-daily SC injection due to albumin-binding extension. Cardiovascular benefit demonstrated in LEADER trial (reduction in MACE).',
      adverse_effects: 'Nausea and vomiting (most common, transient with titration); diarrhoea; injection site reactions; pancreatitis (rare); medullary thyroid carcinoma signal in rodents (C-cell hyperplasia) — CONTRAINDICATED in patients with a personal or family history of medullary thyroid carcinoma or MEN type 2 syndrome; weight loss (advantageous but can be excessive).',
      clinical_use: 'Type 2 diabetes with proven cardiovascular disease benefit; obesity treatment (higher-dose formulation); NAFLD. semaglutide (weekly SC or oral) shares the same class with superior weight-loss efficacy in trials such as SUSTAIN and SURMOUNT.',
      memory_hook: 'The juice bar serves slow-digesting GLP-1 formula all day — hearts get stronger, waistlines shrink, but the bar is off-limits to anyone with a medullary thyroid tumour sign above the door.',
      source: 'G&G 14e, ch. 51',
      high_yield: true,
    },
    {
      id: 'empagliflozin',
      district: 'endocrine',
      building: 'the SGLT2 kidney-sluice house at the proximal tubule quay of the islet district',
      class: 'SGLT2 inhibitor; glucosuric antidiabetic',
      mechanism: 'Inhibits sodium-glucose cotransporter 2 (SGLT2) in the S1–S2 segment of the proximal renal tubule, blocking the reabsorption of approximately 90% of filtered glucose. Glucose is excreted in the urine (glycosuria), lowering plasma glucose independently of insulin. Additional haemodynamic and metabolic effects: reduced preload and afterload (natriuresis), lower uric acid, improved renal oxygen delivery, erythropoietin stimulation. Cardiovascular mortality, heart failure hospitalisation, and CKD progression reduction demonstrated in EMPA-REG OUTCOME, EMPEROR-Reduced, and EMPA-KIDNEY.',
      adverse_effects: 'Genital mycotic infections (candidiasis, owing to glucosuria providing fungal substrate); urinary tract infections; polyuria; hypotension (dehydration, especially in elderly and diuretic users); euglycaemic DKA — SGLT2 inhibitors shift metabolism toward ketogenesis; euglycaemic DKA is a serious and under-recognised risk particularly in type 1 diabetes and perioperative fasting (SGLT2 inhibitors MUST be withheld before surgery and in T1DM); Fournier gangrene (rare but serious necrotising perineal fasciitis).',
      clinical_use: 'Type 2 diabetes with established CVD or high CVD risk; heart failure (both reduced and preserved ejection fraction); CKD with proteinuria. Avoid in T1DM. Withheld at least 3 days before elective surgery.',
      memory_hook: 'The sluice house dumps glucose into the river instead of letting it back into the city — the city floods less (lower cardiac preload), but the riverbank grows fungus and the metabolism tips toward ketones when the city fasts.',
      source: 'G&G 14e, ch. 51',
      high_yield: true,
    },
    {
      id: 'acarbose',
      district: 'endocrine',
      building: 'the α-glucosidase toll-gate at the intestinal starch market',
      class: 'Alpha-glucosidase inhibitor; intestinal glucose-absorption retarder',
      mechanism: 'Competitively inhibits α-glucosidases (maltase, sucrase, glucoamylase) in the small intestinal brush border, delaying hydrolysis of complex carbohydrates and disaccharides to monosaccharides. Blunts postprandial glucose excursion. Does not stimulate insulin secretion → no intrinsic hypoglycaemia. Undigested carbohydrates pass to the colon where bacterial fermentation produces gas.',
      adverse_effects: 'Flatulence, abdominal bloating, and diarrhoea (common, often dose-limiting — caused by colonic fermentation of unabsorbed carbohydrates); elevated liver transaminases at high doses; if hypoglycaemia occurs while on acarbose (from another agent), it MUST be treated with glucose (not sucrose/table sugar, which cannot be digested rapidly).',
      clinical_use: 'Type 2 diabetes as adjunct therapy; effective primarily for post-prandial hyperglycaemia. Limited use in practice due to GI intolerability. Taken at the start of each main meal.',
      memory_hook: 'The toll-gate slows every starch cart crossing the intestinal bridge — glucose arrives at the bloodstream in a trickle rather than a flood, but the fermentation fumes are everyone\'s problem.',
      source: 'G&G 14e, ch. 51',
      high_yield: false,
    },

    // ─── THYROID ──────────────────────────────────────────────────────────────

    {
      id: 'levothyroxine',
      district: 'endocrine',
      building: 'the T4 replacement temple at the upper thyroid terrace',
      class: 'Synthetic L-thyroxine (T4); thyroid hormone replacement',
      mechanism: 'Exogenous T4 is converted peripherally (mainly in liver and kidney) to the active T3 by deiodinase enzymes. T3 binds nuclear thyroid hormone receptors (TRα, TRβ) and regulates transcription of genes governing basal metabolic rate, cardiovascular function, development, and growth. T4 has a half-life of ~7 days owing to high protein binding (TBG, TTR, albumin).',
      adverse_effects: 'Iatrogenic hyperthyroidism (thyrotoxicosis) if over-replaced: palpitations, tachycardia, atrial fibrillation, bone loss, weight loss, anxiety, heat intolerance; interactions with warfarin (increases anticoagulant effect), antacids/calcium/iron reduce absorption; soy and fibre interfere with absorption.',
      clinical_use: 'Hypothyroidism (first-line lifelong replacement); TSH suppression in differentiated thyroid cancer post-thyroidectomy. Taken on an empty stomach 30–60 min before food for consistent absorption. Dose titrated to TSH normalisation.',
      memory_hook: 'The T4 temple is the cornerstone of the thyroid terrace — one tablet every morning restores the hormonal order, but over-supply sets the city on fire.',
      source: 'G&G 14e, ch. 52',
      high_yield: true,
    },
    {
      id: 'carbimazole',
      district: 'endocrine',
      building: 'the thionamide blockade-post at the thyroid peroxidase gate',
      class: 'Thionamide (prodrug of methimazole); antithyroid agent',
      mechanism: 'Carbimazole is converted to methimazole in the body. Methimazole inhibits thyroid peroxidase (TPO), blocking organification of iodide (the step that incorporates iodine into tyrosyl residues of thyroglobulin) and coupling of iodotyrosines (T3 and T4 synthesis). Does NOT block secretion of pre-formed stored hormone — clinical effect is delayed 1–3 weeks until existing hormone is depleted.',
      adverse_effects: 'Agranulocytosis (rare, ~0.3%, but potentially fatal — warn patient to seek immediate blood count if fever, sore throat, or mouth ulcers develop); rash and pruritus; hepatotoxicity (less than PTU); vasculitis (ANCA-positive); hypothyroidism if over-treated. TERATOGEN IN THE FIRST TRIMESTER — associated with aplasia cutis, choanal atresia, and tracheo-oesophageal fistula (methimazole embryopathy). Use propylthiouracil (PTU) in the first trimester instead.',
      clinical_use: 'Graves\' disease (hyperthyroidism); toxic multinodular goitre; Graves\' ophthalmopathy (as part of thyroid control); pre-operative preparation before thyroidectomy. Switch to PTU in first-trimester pregnancy.',
      memory_hook: 'The blockade-post clamps the peroxidase gate — no new iodination orders get through, but the post is closed for the first three months of pregnancy when PTU must man the gate instead.',
      source: 'G&G 14e, ch. 52',
      high_yield: true,
    },
    {
      id: 'propylthiouracil',
      district: 'endocrine',
      building: 'the PTU first-trimester guard-house and T4-to-T3 conversion checkpoint',
      class: 'Thionamide; antithyroid agent; peripheral T4→T3 conversion inhibitor',
      mechanism: 'Like methimazole, inhibits TPO → blocks synthesis of T3/T4 (organification and coupling). Uniquely also inhibits peripheral 5-deiodinase → blocks conversion of T4 to active T3 in peripheral tissues. This dual action makes PTU the preferred agent in thyroid storm. PTU is highly protein-bound → less placental transfer than carbimazole/methimazole → used in the first trimester to avoid methimazole embryopathy.',
      adverse_effects: 'Hepatotoxicity (fulminant hepatic necrosis — rare but serious; FDA black box warning; risk higher than carbimazole; monitor LFTs; discontinue immediately if jaundice or elevated transaminases); agranulocytosis; rash; vasculitis; lupus-like syndrome.',
      clinical_use: 'First-trimester pregnancy (preferred over carbimazole/methimazole to avoid embryopathy); thyroid storm (dual inhibition of synthesis and peripheral conversion); Graves\' disease when carbimazole is not tolerated.',
      memory_hook: 'The PTU guard-house is the only one trusted to work in the first trimester, and it blocks both the thyroid factory and the tissue conversion depot — but its liver record is under investigation.',
      source: 'G&G 14e, ch. 52',
      high_yield: true,
    },
    {
      id: 'radioactive_iodine',
      district: 'endocrine',
      building: 'the I-131 ablation furnace at the base of the thyroid terrace',
      class: 'Iodine-131; definitive antithyroid therapy / thyroid cancer ablation',
      mechanism: 'Iodine-131 is taken up by thyroid follicular cells via the sodium-iodide symporter (NIS) in exactly the same way as stable iodine. Once inside the follicular cell, I-131 emits beta radiation (and gamma, used for imaging) that destroys the surrounding thyroid parenchyma. Ablation is permanent — hypothyroidism is the expected long-term outcome (not an adverse effect, but the therapeutic goal in most cases).',
      adverse_effects: 'Radiation thyroiditis (transient neck pain, swelling, release of stored hormone — can precipitate thyroid storm; pretreat with antithyroid drugs); hypothyroidism (expected outcome, treated with lifelong levothyroxine); dry mouth / salivary gland inflammation (high-dose ablation for thyroid cancer); radiation safety precautions required (avoid close contact with pregnant women and children for days after treatment).',
      clinical_use: 'Graves\' disease (definitive treatment, especially with recurrence or intolerance to antithyroid drugs); toxic multinodular goitre; toxic adenoma; remnant ablation after thyroidectomy for differentiated thyroid cancer. CONTRAINDICATED in pregnancy and breastfeeding.',
      memory_hook: 'The ablation furnace runs on thyroid\'s own iodine greed — the NIS symporter swallows I-131 believing it is nutrition, and the beta-radiation burns the furnace down from inside.',
      source: 'G&G 14e, ch. 52',
      high_yield: true,
    },

    // ─── CORTICOSTEROIDS ──────────────────────────────────────────────────────

    {
      id: 'hydrocortisone',
      district: 'endocrine',
      building: 'the replacement-pillar at the centre of the adrenal courtyard',
      class: 'Natural glucocorticoid (also weak mineralocorticoid); cortisol equivalent',
      mechanism: 'Binds cytoplasmic glucocorticoid receptor (GR-α) → receptor-ligand complex translocates to nucleus → binds glucocorticoid response elements (GREs) → upregulates anti-inflammatory genes (annexin-1, lipocortin, IL-10) and downregulates pro-inflammatory transcription factors (NF-κB, AP-1) → reduces synthesis of COX-2, phospholipase A2, and cytokines. Also has mineralocorticoid activity at physiological cortisol doses (retains sodium).',
      adverse_effects: 'In replacement doses: minimal. In pharmacological doses: Cushingoid features (central obesity, striae, moon face, buffalo hump), hyperglycaemia, hypertension, osteoporosis, cataracts, peptic ulceration, adrenal suppression (HPA axis). ABRUPT WITHDRAWAL AFTER CHRONIC USE causes adrenal crisis (Addisonian crisis) — hypotension, hyponatraemia, hyperkalaemia, hypoglycaemia, collapse. Must be tapered.',
      clinical_use: 'Addison\'s disease (primary adrenal insufficiency — essential replacement therapy, combined with fludrocortisone); adrenal crisis (high-dose IV hydrocortisone is life-saving); congenital adrenal hyperplasia (replacement + suppression of ACTH-driven androgen excess); anaphylaxis (adjunct).',
      memory_hook: 'The replacement pillar holds the adrenal courtyard up — remove it suddenly and the whole courtyard collapses into an Addisonian crisis; taper out one stone at a time.',
      source: 'G&G 14e, ch. 50',
      high_yield: true,
    },
    {
      id: 'prednisolone',
      district: 'endocrine',
      building: 'the anti-inflammatory colonnade of the glucocorticoid tier',
      class: 'Synthetic glucocorticoid; anti-inflammatory and immunosuppressant',
      mechanism: 'Activates GR-α with ~4× greater potency than hydrocortisone; minimal mineralocorticoid activity at anti-inflammatory doses. Suppresses inflammatory cascades via GRE-mediated gene regulation: inhibits NF-κB, reduces production of TNF-α, IL-1, IL-6, prostaglandins, and leukotrienes; stabilises mast cells and basophils; reduces vascular permeability; redistributes lymphocytes out of the circulation.',
      adverse_effects: 'HPA-axis suppression (all patients on corticosteroids for >3 weeks are at risk — NEVER stop abruptly; taper over weeks to months); hyperglycaemia; osteoporosis (activate bisphosphonate prophylaxis for anticipated long-term therapy); myopathy; avascular necrosis (femoral head); peptic ulceration (especially with NSAIDs); increased susceptibility to infection (including opportunistic infections — reactivation of TB, fungal infections); cataracts; psychiatric effects (insomnia, euphoria, depression, psychosis); Cushingoid features.',
      clinical_use: 'Asthma exacerbations; COPD exacerbations; rheumatoid arthritis; SLE; IBD; nephrotic syndrome; minimal change nephropathy; organ transplant rejection prophylaxis; polymyalgia rheumatica; temporal arteritis; immune thrombocytopenic purpura; myasthenia gravis; multiple sclerosis relapses.',
      memory_hook: 'The anti-inflammatory colonnade is magnificent and broad — but every pillar added represents a side effect, and when the warden decides to tear them down, he must do it one pillar per week or the whole portico crashes.',
      source: 'G&G 14e, ch. 50',
      high_yield: true,
    },
    {
      id: 'dexamethasone',
      district: 'endocrine',
      building: 'the high-potency command tower at the back of the adrenal courtyard',
      class: 'Potent synthetic glucocorticoid (no mineralocorticoid activity)',
      mechanism: 'Binds GR-α with ~25–30× potency relative to hydrocortisone; essentially zero mineralocorticoid activity. Long half-life (~36–72 h). Crosses the placenta efficiently (unlike prednisolone, which is inactivated by placental 11β-HSD2). Suppresses pituitary ACTH secretion potently → used in the low-dose dexamethasone suppression test to screen for Cushing\'s syndrome.',
      adverse_effects: 'Same Cushingoid profile as prednisolone; cerebral oedema management may include raised blood glucose; HPA suppression; fetal exposure (though intentional in pre-term labour).',
      clinical_use: 'Cerebral oedema (tumour-associated, post-neurosurgery); raised intracranial pressure; croup (single dose reduces laryngeal oedema); bacterial meningitis (adjunct — reduces hearing loss from inflammation); COVID-19 (RECOVERY trial: reduced mortality on oxygen or ventilator); pre-natal lung maturation (antenatal corticosteroids for fetal lung surfactant — one course at 24–34 weeks); anti-emesis in chemotherapy; high-dose in multiple myeloma and lymphoma regimens; diagnostic (dexamethasone suppression test).',
      memory_hook: 'The command tower broadcasts the loudest suppression signal — it is the only steroid that reaches the fetus cleanly and the only one that appears in the RECOVERY trial bulletin board.',
      source: 'G&G 14e, ch. 50',
      high_yield: true,
    },
    {
      id: 'fludrocortisone',
      district: 'endocrine',
      building: 'the mineralocorticoid salt-vault at the lower tier of the adrenal courtyard',
      class: 'Synthetic mineralocorticoid; potent aldosterone-like agent',
      mechanism: 'Binds mineralocorticoid receptors (MR) in the renal collecting duct with high affinity, promoting transcription of ENaC (epithelial sodium channel) and Na/K-ATPase → sodium and water retention; potassium excretion. 10× more potent than aldosterone; also has glucocorticoid activity (~10× hydrocortisone). Very long half-life → once-daily dosing.',
      adverse_effects: 'Hypertension; oedema; hypokalaemia; hypomagnesaemia; excessive sodium retention; Cushingoid effects from its glucocorticoid component.',
      clinical_use: 'Addison\'s disease (primary adrenal insufficiency — replaces aldosterone alongside hydrocortisone; essential for BP and electrolyte homeostasis); salt-wasting congenital adrenal hyperplasia; orthostatic hypotension (autonomic neuropathy, multiple system atrophy).',
      memory_hook: 'The salt-vault locks sodium in and throws potassium out — without it, the Addisonian villager collapses every time they stand up in the heat.',
      source: 'G&G 14e, ch. 50',
      high_yield: true,
    },

    // ─── SEX HORMONES & CONTRACEPTIVES ───────────────────────────────────────

    {
      id: 'combined_oral_contraceptive',
      district: 'endocrine',
      building: 'the estrogen-progestin combination stall at the gonadal pavilion',
      class: 'Combined oral contraceptive pill (COCP); estrogen + progestin',
      mechanism: 'Estrogen component (ethinylestradiol) suppresses FSH secretion via negative feedback on the pituitary → prevents follicular development. Progestin component suppresses LH surge → prevents ovulation; thickens cervical mucus (hostile to sperm); thins endometrial lining (hostile to implantation). Combined effect yields >99% contraceptive efficacy with perfect use.',
      adverse_effects: 'Venous thromboembolism (VTE) — estrogen increases hepatic synthesis of clotting factors (II, VII, VIII, X, fibrinogen) and decreases protein S; risk higher with third/fourth-generation progestins (desogestrel, drospirenone); CONTRAINDICATED in personal history of VTE, thrombophilia, immobility; nausea; breakthrough bleeding; mild hypertension; mood changes; hepatic adenoma (rare, associated with long-term use); cholestasis; decreased libido; breast tenderness; drug interactions: rifampicin and enzyme-inducing anticonvulsants reduce efficacy.',
      clinical_use: 'Contraception; dysmenorrhoea; endometriosis; polycystic ovary syndrome (regulate cycle, reduce androgenism); acne (anti-androgenic progestins); menorrhagia; premenstrual dysphoric disorder.',
      memory_hook: 'The combination stall sells two signals: the estrogen shuts the FSH factory and the progestin throws a thick gate across the cervix — but the estrogen also tips the clotting balance toward thrombosis.',
      source: 'G&G 14e, ch. 44',
      high_yield: true,
    },
    {
      id: 'tamoxifen',
      district: 'endocrine',
      building: 'the SERM selective-receptor-modulator tower at the breast-cancer ward of the gonadal pavilion',
      class: 'Selective estrogen receptor modulator (SERM); antiestrogen in breast tissue',
      mechanism: 'Binds estrogen receptor (ER) competitively. Acts as an ER ANTAGONIST in breast tissue (blocks estrogen-driven proliferation of ER+ cancer cells) but as an ER AGONIST in bone (protects bone density) and uterus. Tamoxifen is a prodrug partially converted to the active metabolite endoxifen by CYP2D6. Reduces recurrence and mortality in ER-positive breast cancer by approximately 50%.',
      adverse_effects: 'Hot flushes; vaginal discharge; mood changes; VTE (estrogen-agonist effect on coagulation factors in liver → increased clotting factors); ENDOMETRIAL CANCER — ER agonism in the uterus stimulates endometrial proliferation; requires annual gynaecological surveillance for postmenopausal users; cataract; liver enzyme elevation; drug interaction with CYP2D6 inhibitors (paroxetine, fluoxetine) reduces endoxifen formation → reduced efficacy (avoid these antidepressants in tamoxifen users).',
      clinical_use: 'Adjuvant therapy for ER-positive breast cancer (pre- and postmenopausal); ductal carcinoma in situ (DCIS); chemoprevention in high-risk women; male breast cancer.',
      memory_hook: 'The SERM tower is a friend in the breast ward and a foe in the uterine chamber — it blocks the estrogen signal in one room but switches it on next door, and the VTE flood always threatens the corridors.',
      source: 'G&G 14e, ch. 45',
      high_yield: true,
    },
    {
      id: 'raloxifene',
      district: 'endocrine',
      building: 'the bone-protective SERM archive at the osteoporosis wing of the gonadal pavilion',
      class: 'Selective estrogen receptor modulator (SERM); ER agonist in bone, antagonist in breast and uterus',
      mechanism: 'Binds ER with same affinity as estradiol. Tissue-selective co-activator recruitment profile: ER AGONIST in bone (increases bone density, reduces vertebral fractures) and cardiovascular tissue; ER ANTAGONIST in breast and endometrium. Unlike tamoxifen, does not stimulate uterine proliferation → no endometrial cancer risk.',
      adverse_effects: 'VTE (deep vein thrombosis, pulmonary embolism — same clotting-factor agonism as tamoxifen; CONTRAINDICATED in patients with prior VTE); hot flushes (worsens vasomotor symptoms — not suitable for menopausal symptom relief); leg cramps.',
      clinical_use: 'Osteoporosis prevention and treatment in postmenopausal women (reduces vertebral fracture risk; not effective for hip fractures unlike bisphosphonates); reduction of ER-positive invasive breast cancer risk in high-risk postmenopausal women (STAR trial). Less effective for osteoporosis than bisphosphonates or denosumab.',
      memory_hook: 'The SERM archive keeps bone records intact and locks the uterine filing cabinet — but the VTE courier still runs the same dangerous errand through the coagulation district.',
      source: 'G&G 14e, ch. 45',
      high_yield: true,
    },
    {
      id: 'anastrozole',
      district: 'endocrine',
      building: 'the aromatase foundry shutdown valve in the postmenopausal estrogen wing',
      class: 'Non-steroidal aromatase inhibitor (third generation); antiestrogen',
      mechanism: 'Competitively inhibits aromatase (CYP19A1), the enzyme that catalyses conversion of androgens (androstenedione, testosterone) to estrogens (estrone, estradiol) in peripheral tissues (adipose, breast stroma, liver). In postmenopausal women — where ovarian estrogen production has ceased — peripheral aromatisation is the primary estrogen source; anastrozole blocks >98% of this. Does not block adrenal or pituitary steroidogenesis of non-estrogenic steroids.',
      adverse_effects: 'Arthralgias and myalgias (very common, can lead to non-adherence); hot flushes; vaginal dryness; bone loss / osteoporosis (estrogen deprivation reduces bone density — baseline DXA and bisphosphonate prophylaxis if needed); hypercholesterolaemia; increased cardiovascular risk vs tamoxifen in some trials.',
      clinical_use: 'Adjuvant therapy for postmenopausal ER-positive breast cancer (superior to tamoxifen in postmenopausal women in terms of disease-free survival in ATAC trial); advanced and metastatic ER+ breast cancer. NOT appropriate in premenopausal women unless combined with ovarian suppression. Other agents: letrozole, exemestane.',
      memory_hook: 'The foundry shutdown valve closes the androgen-to-estrogen conversion entirely — postmenopausal breast cancer withers when its estrogen supply is cut at the peripheral foundry.',
      source: 'G&G 14e, ch. 45',
      high_yield: true,
    },
    {
      id: 'finasteride',
      district: 'endocrine',
      building: 'the 5-α-reductase enzyme-lock at the DHT processing plant on the androgen terrace',
      class: '5-α-reductase inhibitor (type II); antiandrogen; BPH and alopecia therapy',
      mechanism: 'Competitively inhibits type II 5-α-reductase, the enzyme that converts testosterone to the more potent dihydrotestosterone (DHT) in the prostate, skin, and hair follicles. DHT drives prostatic stromal and glandular cell proliferation (BPH) and follicular miniaturisation (androgenic alopecia). Finasteride reduces prostatic DHT by >90% and serum DHT by ~70%. Does not block testosterone binding to the androgen receptor.',
      adverse_effects: 'Sexual dysfunction (decreased libido, erectile dysfunction, ejaculatory dysfunction — can persist after stopping, "post-finasteride syndrome"); gynaecomastia; rare breast cancer; depression has been reported; TERATOGENOUS — finasteride is a Category X teratogen; DHT is essential for male fetal external genital development; PREGNANT WOMEN MUST NOT HANDLE CRUSHED OR BROKEN TABLETS owing to transcutaneous absorption risk (male fetus exposure → ambiguous genitalia). Whole coated tablets are safe to handle.',
      clinical_use: 'Benign prostatic hyperplasia (reduces prostate volume, improves urinary symptoms; takes 3–6 months for full effect; reduces risk of acute urinary retention and need for surgery); androgenic alopecia (male-pattern hair loss); chemoprevention of prostate cancer (reduces incidence but may increase proportion of high-grade cancers — not routinely recommended).',
      memory_hook: 'The enzyme-lock blocks DHT production — the prostate shrinks, the hairline holds — but the "no crushing" sign on every tablet is non-negotiable: powdered finasteride on a pregnant woman\'s hands reaches a male fetus and scrambles his urogenital blueprint.',
      source: 'G&G 14e, ch. 45',
      high_yield: true,
    },

    // ─── BONE & CALCIUM ───────────────────────────────────────────────────────

    {
      id: 'alendronate',
      district: 'endocrine',
      building: 'the bisphosphonate osteoclast-trap at the bone mineral market',
      class: 'Nitrogen-containing bisphosphonate; anti-resorptive bone agent',
      mechanism: 'Incorporates into the hydroxyapatite matrix of bone at sites of active remodelling, specifically at osteoclast-bone interfaces. When osteoclasts resorb bone and ingest bisphosphonate-coated mineral, the drug inhibits farnesyl diphosphate synthase (a mevalonate pathway enzyme) → disrupts the prenylation of small GTPases (Ras, Rho, Rac) → impairs osteoclast cytoskeletal function and survival → apoptosis of osteoclasts. Net effect: profound and prolonged reduction in bone resorption; bone mineral density increases.',
      adverse_effects: 'Oesophagitis and oesophageal ulceration (MAJOR) — must be taken on an empty stomach with a full glass of water; patient must remain upright for ≥30 minutes after ingestion; CONTRAINDICATED in oesophageal stricture or achalasia; atypical subtrochanteric (femoral shaft) fractures with long-term use (>5 years); osteonecrosis of the jaw (ONJ) — particularly with high-dose IV bisphosphonates for malignancy, but reported with oral use too; DENTAL WORK MUST BE COMPLETED BEFORE STARTING bisphosphonates if invasive dental procedures are anticipated; hypocalcaemia; acute-phase response (flu-like symptoms with IV bisphosphonates).',
      clinical_use: 'Osteoporosis treatment and prevention (postmenopausal, glucocorticoid-induced); Paget\'s disease of bone; hypercalcaemia of malignancy (IV bisphosphonates). Weekly oral dosing (alendronate) improves adherence. Risedronate has a similar profile.',
      memory_hook: 'The osteoclast-trap lures osteoclasts with mineral bait then poisons their mevalonate engine — but the trap rules are strict: no lying down after swallowing, no skipping the dental inspection, and after five years watch for the femoral fault-line crack.',
      source: 'G&G 14e, ch. 53',
      high_yield: true,
    },
    {
      id: 'denosumab',
      district: 'endocrine',
      building: 'the RANKL antibody customs post at the osteoclast recruitment gate',
      class: 'Monoclonal antibody (IgG2) against RANKL; anti-resorptive bone agent',
      mechanism: 'Fully human monoclonal antibody that binds RANKL (receptor activator of NF-κB ligand), preventing its interaction with RANK on osteoclast precursors and mature osteoclasts. Without the RANKL signal, osteoclast differentiation, function, and survival are suppressed → bone resorption decreases. Unlike bisphosphonates, denosumab is not incorporated into bone matrix and its effects are fully reversible on discontinuation. Given SC every 6 months.',
      adverse_effects: 'Hypocalcaemia (ensure vitamin D and calcium adequacy before and during treatment); osteonecrosis of the jaw (lower risk than IV bisphosphonates but same principle — dental review before starting); atypical femoral fractures (class effect); infection risk (RANKL expressed on immune cells — increased susceptibility to serious infections, particularly cellulitis); REBOUND VERTEBRAL FRACTURE PHENOMENON on discontinuation — rapid loss of bone density and multiple vertebral fractures within 12–18 months of stopping (transition to a bisphosphonate is recommended to prevent rebound).',
      clinical_use: 'Postmenopausal osteoporosis; osteoporosis in men; glucocorticoid-induced osteoporosis; bone metastases and skeletal-related events (higher dose); giant cell tumour of bone.',
      memory_hook: 'The RANKL customs post turns away every osteoclast-recruitment order while denosumab is on duty — but the moment the guard stands down, a year\'s worth of pending orders arrive and multiple vertebrae crumble in a rebound crush.',
      source: 'G&G 14e, ch. 53',
      high_yield: true,
    },
    {
      id: 'teriparatide',
      district: 'endocrine',
      building: 'the PTH analogue osteoblast-activation workshop on the bone-building terrace',
      class: 'Recombinant human PTH (1-34) fragment; anabolic bone agent',
      mechanism: 'Intermittent SC administration of PTH (1-34) activates the PTH/PTHrP receptor (PTHR1) on osteoblasts → pulsatile stimulation increases osteoblast number and activity (via Wnt signalling upregulation and sclerostin suppression) → net bone formation. Paradoxically, continuous PTH (as in primary hyperparathyroidism) causes bone loss; intermittent pulses are anabolic. Increases bone mineral density in both trabecular and cortical bone.',
      adverse_effects: 'Hypercalcaemia (transient, post-injection); nausea; leg cramps; orthostatic hypotension (dizziness post-injection); osteosarcoma in rats (dose- and duration-dependent — duration of use limited to a cumulative 2-year maximum; CONTRAINDICATED in patients with history of prior radiation therapy to the skeleton, Paget\'s disease, prior osteosarcoma, or unexplained alkaline phosphatase elevation).',
      clinical_use: 'Severe osteoporosis at high fracture risk (failed bisphosphonate, very low BMD T-score, multiple prior fractures); glucocorticoid-induced osteoporosis when anti-resorptive therapy is insufficient. Must be followed by anti-resorptive therapy (bisphosphonate or denosumab) to consolidate anabolic gains.',
      memory_hook: 'The osteoblast workshop runs at full production when pulsed with PTH — but the furnace is rated for only two years before the osteosarcoma risk in the rat trial forces a closure notice.',
      source: 'G&G 14e, ch. 53',
      high_yield: true,
    },

    // ─── POSTERIOR PITUITARY / PITUITARY ──────────────────────────────────────

    {
      id: 'desmopressin',
      district: 'endocrine',
      building: 'the V2 receptor vasopressin analogue fountain at the pituitary summit',
      class: 'Synthetic vasopressin (ADH) analogue; V2 receptor agonist',
      mechanism: 'Desmopressin (1-deamino-8-d-arginine vasopressin) binds V2 receptors on renal collecting duct principal cells → activates adenylyl cyclase → cAMP-dependent phosphorylation → insertion of aquaporin-2 water channels into the apical membrane → water reabsorption (antidiuresis). Also binds V2 receptors on endothelial cells (via a different intracellular pathway involving IP3 and Ca²⁺) → release of von Willebrand factor (vWF) and factor VIII from Weibel-Palade bodies. The deamination at position 1 removes pressor activity (V1 vasoconstriction); d-Arg8 substitution prolongs half-life to ~8 hours.',
      adverse_effects: 'Hyponatraemia and water intoxication (dangerous if fluid intake is not restricted; especially in children, elderly, and psychogenic polydipsia contexts — can cause seizures and cerebral oedema); headache; flushing; nausea; facial flushing. Avoid concurrent use with excessive free water.',
      clinical_use: 'Central diabetes insipidus (replacement therapy, oral/nasal/SC/IV/IM); nocturnal enuresis in children (reduces overnight urine production); haemophilia A and von Willebrand disease type 1 (releases vWF and factor VIII — used before minor procedures); primary nocturnal enuresis in adults.',
      memory_hook: 'The pituitary fountain runs desmopressin (not the original vasopressin — the deaminated safer cousin) through the collecting duct pipe, locking aquaporins open and releasing vWF from the endothelial storehouse when the coagulation district calls.',
      source: 'G&G 14e, ch. 48',
      high_yield: true,
    },
    {
      id: 'octreotide',
      district: 'endocrine',
      building: 'the somatostatin analogue relay tower on the pituitary summit ridge',
      class: 'Somatostatin analogue; SSTR2/5 agonist; inhibitor of GH, glucagon, insulin secretion',
      mechanism: 'Synthetic octapeptide that mimics somatostatin but has a much longer half-life (~2 h vs. <2 min for native somatostatin). Activates somatostatin receptors (predominantly SSTR2 and SSTR5) on: (1) pituitary somatotrophs → suppresses GH secretion; (2) pancreatic alpha and beta cells → suppresses glucagon and insulin; (3) splanchnic vasculature → vasoconstriction (reduces portal blood flow); (4) GI neuroendocrine cells → suppresses VIP, serotonin, substance P (reduces secretions and motility).',
      adverse_effects: 'GI symptoms (nausea, diarrhoea, abdominal cramping, steatorrhoea — due to reduced exocrine pancreatic secretion and altered GI motility); gallstones (cholestasis from reduced cholecystokinin stimulation — monitor with ultrasound); bradycardia; hyperglycaemia or hypoglycaemia (unpredictable suppression of both insulin and glucagon); local injection site reactions.',
      clinical_use: 'Acromegaly (reduces GH and IGF-1; reduces tumour size; used when surgery is not curative or as bridge to surgery); variceal bleeding (acute — reduces splanchnic blood flow; replaces vasopressin/terlipressin in some protocols); carcinoid syndrome (controls flushing and diarrhoea by suppressing serotonin and other vasoactive mediators); VIPoma, glucagonoma, gastrinoma (reduces secretion); dumping syndrome; short-bowel syndrome.',
      memory_hook: 'The relay tower simultaneously quiets the GH broadcast, dials down the insulin and glucagon transmitters, and tightens the splanchnic blood-vessel pipes — a single analogue signal that reaches five different receiver stations.',
      source: 'G&G 14e, ch. 48',
      high_yield: true,
    },
  ],
};

if (typeof window !== 'undefined') window.DISTRICT_ENDOCRINE = DISTRICT_ENDOCRINE;
