const DISTRICT_GIT = {
  id: 'git',
  name: 'GIT',
  theme_line: 'Market row · stalls and digestion',
  walkthrough: `Market Row is the city's great digestive bazaar — a long, chaotic avenue of stalls where every booth represents a drug acting on the stomach, small intestine, colon, or the neural plumbing that connects them all. The smells of acid, bile, and fermentation hang in the air, and the dominant sound is the rhythmic churning of the proton-pump factories at the top of the street.

The proton-pump inhibitor (PPI) stalls are the most prominent — five similar-looking booths selling omeprazole, pantoprazole, esomeprazole, and their siblings. All five irreversibly bind and inactivate the H+/K+-ATPase proton pump on the canalicular membrane of gastric parietal cells. The parietal cell must synthesise new pumps before gastric acid secretion can resume, which is why PPIs require 3–5 days to reach full effect and why they should be taken 30 minutes before meals (to catch pumps actively inserting into the canalicular membrane). The warning sign above the pantoprazole stall flags a common examination trap: clopidogrel, the antiplatelet prodrug, requires CYP2C19 for bioactivation — and the PPIs that most inhibit CYP2C19 (especially esomeprazole and omeprazole) reduce clopidogrel efficacy. Pantoprazole, a weaker CYP2C19 inhibitor, is the preferred PPI with clopidogrel.

Further down the row, the prokinetic stalls line the middle section. Metoclopramide is the city's controversial drug-runner — a D2 antagonist who also serotonin-sensitises the gut, accelerating gastric emptying and raising lower oesophageal sphincter tone. Its boxed warning reads "Chronic use causes tardive dyskinesia — a movement disorder that may be irreversible." Next door, domperidone runs a slightly cleaner operation: it stays mostly outside the blood-brain barrier and focuses its D2 blockade on the gut, but its cardiac risk (QT prolongation) requires caution.

At the far end of the row, the IBD biologics occupy a new, gleaming precinct. Mesalazine holds the intestinal wall stall; adalimumab and vedolizumab occupy the immunological tower — targeting TNF-alpha and gut-selective integrins respectively.`,
  palette: { ground: 0xD4A96A, accent: 0x8B4513, water: 0x4682B4 },
  position: { x: 0, z: 50 },
  drugs: [
    {
      id: 'omeprazole',
      district: 'git',
      building: 'the flagship PPI factory at the top of market row',
      class: 'Proton pump inhibitor (PPI); irreversible H+/K+-ATPase inhibitor',
      mechanism: 'A prodrug activated in the acidic environment of the secretory canaliculus of gastric parietal cells. The active sulfenamide metabolite covalently binds cysteine residues on the luminal surface of H+/K+-ATPase (the proton pump), irreversibly inactivating it. Acid secretion from that pump ceases until new pumps are synthesised. Should be taken before meals (30 min) to coincide with pumps actively inserting into the canalicular membrane. Metabolised by CYP2C19; omeprazole is a moderate inhibitor of CYP2C19.',
      adverse_effects: 'Hypomagnesaemia (chronic use — impairs Mg2+ absorption; can cause tetany, arrhythmia); vitamin B12 deficiency (acid needed for intrinsic factor function and B12 absorption); increased risk of C. difficile infection (altered GI flora); increased risk of osteoporotic fractures (impaired calcium absorption in alkaline environment); community-acquired pneumonia (altered gastric pH may permit bacterial colonisation); CYP2C19 interaction: reduces clopidogrel activation → reduced antiplatelet efficacy.',
      clinical_use: 'Peptic ulcer disease; GORD; Helicobacter pylori eradication (triple or quadruple therapy); stress ulcer prophylaxis in ICU; Zollinger-Ellison syndrome; NSAID-associated gastric protection.',
      memory_hook: 'Omeprazole is the flagship PPI stall — it permanently shutters the acid pump until new ones are built. But its CYP2C19 shadow means it quietly pickpockets clopidogrel\'s effectiveness next door.',
      source: 'G&G 14e, ch. 49',
      high_yield: true,
    },
    {
      id: 'pantoprazole',
      district: 'git',
      building: 'the clopidogrel-safe PPI counter with the cardiology approval seal',
      class: 'Proton pump inhibitor (PPI); irreversible H+/K+-ATPase inhibitor',
      mechanism: 'Same mechanism as omeprazole — activated in the parietal cell canaliculus, covalently binds H+/K+-ATPase cysteines. Pantoprazole is a notably weaker inhibitor of CYP2C19 than omeprazole or esomeprazole. This pharmacokinetic difference reduces the risk of impairing clopidogrel bioactivation, making it the preferred PPI in patients on clopidogrel for cardiovascular indications.',
      adverse_effects: 'Similar to other PPIs: hypomagnesaemia; vitamin B12 deficiency; C. difficile risk; fracture risk; generally minimal CYP2C19-mediated drug interactions at clinical doses.',
      clinical_use: 'Peptic ulcer; GORD; H. pylori eradication; preferred PPI with clopidogrel (least CYP2C19 inhibition); stress ulcer prophylaxis (IV pantoprazole commonly used in hospitalised patients).',
      memory_hook: 'Pantoprazole is the politically safe PPI — it does the same acid job as omeprazole but leaves the clopidogrel bioactivation lane clear.',
      source: 'G&G 14e, ch. 49',
      high_yield: true,
    },
    {
      id: 'esomeprazole',
      district: 'git',
      building: 'the S-enantiomer PPI stall with the CYP2C19 caution flag',
      class: 'Proton pump inhibitor (PPI); irreversible H+/K+-ATPase inhibitor; S-enantiomer of omeprazole',
      mechanism: 'The S-enantiomer of omeprazole; mechanism identical — activated sulfenamide covalently inactivates parietal cell H+/K+-ATPase. The S-enantiomer has slower CYP2C19-mediated first-pass metabolism than the R-enantiomer (omeprazole is a racemate), resulting in higher systemic bioavailability and a modest increase in acid suppression. Also a moderate-strong CYP2C19 inhibitor — most likely among PPIs to reduce clopidogrel efficacy.',
      adverse_effects: 'Same class effects as omeprazole; higher CYP2C19 inhibition makes it the PPI most likely to interact with clopidogrel. Same risks: hypomagnesaemia, B12 deficiency, C. difficile, fractures.',
      clinical_use: 'GORD; peptic ulcer; H. pylori eradication; Zollinger-Ellison syndrome; erosive oesophagitis — marketed on the basis of slightly higher bioavailability vs omeprazole, though clinical difference in outcomes is marginal for most patients.',
      memory_hook: 'Esomeprazole is the pure S-enantiomer that survives first pass better than its racemic parent — more bioavailable, but its CYP2C19 shadow falls most heavily on clopidogrel next door.',
      source: 'G&G 14e, ch. 49',
      high_yield: true,
    },
    {
      id: 'famotidine',
      district: 'git',
      building: 'the H2 receptor antacid stall — the post-ranitidine era survivor',
      class: 'H2 receptor antagonist',
      mechanism: 'Competitive antagonist at histamine H2 receptors on gastric parietal cells. Histamine (released from enterochromaffin-like cells in response to gastrin) normally activates H2 receptors → adenylyl cyclase → cAMP → PKA → H+/K+-ATPase activation. Blocking H2 receptors reduces basal and food-stimulated acid secretion. Does not inhibit CYP2C19 (unlike cimetidine which inhibits multiple CYP enzymes). Less potent acid suppression than PPIs.',
      adverse_effects: 'Generally well tolerated; headache; dizziness; constipation or diarrhoea; rare: prolonged QTc at high doses; rare thrombocytopenia. Much less inhibition of CYP enzymes than cimetidine. No NDMA contamination (unlike ranitidine which was withdrawn).',
      clinical_use: 'Peptic ulcer disease; GORD (mild-to-moderate); Zollinger-Ellison syndrome; prevention of stress ulcers; as-needed heartburn relief; preferred H2 antagonist since ranitidine withdrawal in 2020.',
      memory_hook: 'Famotidine is the H2 stall survivor — ranitidine left market row due to the NDMA scandal, and famotidine took over as the clean, reliable H2 blocker.',
      source: 'G&G 14e, ch. 49',
      high_yield: true,
    },
    {
      id: 'ranitidine',
      district: 'git',
      building: 'the shuttered H2 stall with the NDMA contamination notice',
      class: 'H2 receptor antagonist — WITHDRAWN (NDMA contamination)',
      mechanism: 'Competitive H2 receptor antagonist — same mechanism as famotidine. Blocks histamine-mediated stimulation of gastric acid secretion. Historically one of the most widely prescribed drugs. Withdrawn globally from 2020 by regulatory agencies after discovery that ranitidine (unlike other H2 blockers) can generate N-nitrosodimethylamine (NDMA), a probable human carcinogen, particularly under elevated storage temperatures.',
      adverse_effects: 'NDMA contamination is the primary safety concern leading to market withdrawal. Previously known adverse effects: headache; dizziness; constipation; rare hepatotoxicity. Mild CYP enzyme inhibition (less than cimetidine).',
      clinical_use: 'Historically used for peptic ulcer disease, GORD, Zollinger-Ellison syndrome. All ranitidine products withdrawn from global markets (2020). Famotidine is the preferred H2 antagonist replacement.',
      memory_hook: 'Ranitidine\'s stall is shuttered — the NDMA ghost in its own molecule ended its market career. Historical significance: it proved H2 blockers could heal peptic ulcers without surgery.',
      source: 'G&G 14e, ch. 49',
      high_yield: false,
    },
    {
      id: 'sucralfate',
      district: 'git',
      building: 'the aluminium-plaster mucosal repair booth at the ulcer site',
      class: 'Mucosal protectant; sucrose octasulfate-aluminium complex',
      mechanism: 'In the acidic gastric environment, sucralfate polymerises into a viscous, sticky substance that binds to the protein-rich ulcer base (positively charged tissue proteins bind the negatively charged sucralfate polymer). Forms a physical barrier protecting the ulcer from acid, pepsin, and bile. Also stimulates prostaglandin synthesis, mucus production, and bicarbonate secretion — cytoprotective effects. Minimal systemic absorption. Requires acid for activation — separate from antacids/PPIs/H2 blockers by at least 2 hours.',
      adverse_effects: 'Constipation (most common — aluminium slows GI motility); aluminium accumulation in renal impairment (do not use in renal failure); interferes with absorption of fluoroquinolones, tetracyclines, digoxin, warfarin, and phenytoin (chelation).',
      clinical_use: 'Peptic ulcer disease (duodenal and gastric ulcers); stress ulcer prophylaxis (equivalent to H2 blockers, with potentially lower risk of nosocomial pneumonia than acid suppressants); GORD (adjunct).',
      memory_hook: 'Sucralfate is the aluminium plaster that sets in acid — it sticks to the raw ulcer surface like cement and protects it from further attack, but must never be mixed with antacid mortar.',
      source: 'G&G 14e, ch. 49',
      high_yield: true,
    },
    {
      id: 'bismuth_subsalicylate',
      district: 'git',
      building: 'the bismuth-pink H. pylori eradication stall at the triple therapy junction',
      class: 'Bismuth salt; mucosal protectant and H. pylori suppressor',
      mechanism: 'Bismuth has antibacterial effects against H. pylori (disrupts the bacterial cell wall and inhibits urease). Also forms a bismuth-protein complex at the ulcer base as a physical protective layer. The salicylate component inhibits prostaglandin synthesis (anti-inflammatory and antidiarrhoeal). Antidiarrhoeal effect: bismuth binds bacterial toxins and stimulates intestinal fluid absorption.',
      adverse_effects: 'Black stool (harmless bismuth sulfide — must warn patients to avoid confusing with melaena); black tongue; constipation; tinnitus and salicylate toxicity with excess use (salicylate component); bismuth encephalopathy (rare, with prolonged high-dose use).',
      clinical_use: 'H. pylori eradication — component of bismuth-based quadruple therapy (bismuth + metronidazole + tetracycline + PPI); travellers\' diarrhoea; non-specific diarrhoea.',
      memory_hook: 'Bismuth subsalicylate is the pink triple-therapy partner — it turns stool black harmlessly while helping to eradicate H. pylori and absorb gut toxins.',
      source: 'G&G 14e, ch. 49',
      high_yield: false,
    },
    {
      id: 'metoclopramide',
      district: 'git',
      building: 'the D2-antagonist prokinetic cart with the tardive dyskinesia warning banner',
      class: 'D2 receptor antagonist; prokinetic; antiemetic',
      mechanism: 'Blocks dopamine D2 receptors in the gut (ENS), the lower oesophageal sphincter, and the chemoreceptor trigger zone (CTZ). In the gut, D2 blockade removes the dopaminergic inhibition of ACh release from myenteric neurons → increased lower oesophageal sphincter tone, increased gastric peristalsis, accelerated gastric emptying, and improved antroduodenal coordination. Also a 5-HT4 agonist in the gut (enhances prokinetic effect). In the CTZ: D2 blockade → antiemetic effect. Crosses the blood-brain barrier.',
      adverse_effects: 'Tardive dyskinesia — potentially irreversible involuntary movements (boxed warning; risk increases with chronic use and higher doses; maximum treatment duration 12 weeks); acute extrapyramidal reactions (dystonia, akathisia, parkinsonism); hyperprolactinaemia (galactorrhoea, gynaecomastia, menstrual irregularities); drowsiness; restlessness; rarely neuroleptic malignant syndrome.',
      clinical_use: 'Gastroparesis (diabetic or post-surgical); GORD; post-operative nausea and vomiting; chemotherapy-induced nausea; nasogastric tube placement facilitation; migraine nausea adjunct.',
      memory_hook: 'Metoclopramide speeds the gut\'s transit by unblocking the D2 brake pedal — but its shadow reaches the brain and can permanently rewire the movement circuits if used too long.',
      source: 'G&G 14e, ch. 49',
      high_yield: true,
    },
    {
      id: 'domperidone',
      district: 'git',
      building: 'the peripheral D2-antagonist prokinetic stall with the QT gauge',
      class: 'D2 receptor antagonist; prokinetic; antiemetic; peripheral-predominant',
      mechanism: 'Blocks D2 receptors in the gastric and upper intestinal smooth muscle and at the CTZ. Does not cross the blood-brain barrier as readily as metoclopramide (due to lower lipophilicity and P-glycoprotein efflux at the BBB), so CNS and extrapyramidal effects are much less common. Prokinetic mechanism similar to metoclopramide. Also blocks cardiac hERG potassium channels → QT interval prolongation.',
      adverse_effects: 'QT prolongation and torsades de pointes (most significant risk — especially at higher doses, in patients with hypokalaemia, or with concurrent QT-prolonging drugs/CYP3A4 inhibitors); hyperprolactinaemia (galactorrhoea, gynaecomastia — because the CTZ is outside the BBB); headache; dry mouth; rare EPS (much less than metoclopramide).',
      clinical_use: 'Gastroparesis; GORD; nausea and vomiting where metoclopramide is not tolerated; Parkinson\'s disease nausea (dopaminergic drugs cause nausea — domperidone treats it without worsening motor symptoms). Avoid in patients on QT-prolonging drugs.',
      memory_hook: 'Domperidone stays mostly outside the brain and is kinder to movement than metoclopramide — but its heart wants to stretch the QT interval, so watch the ECG before and during use.',
      source: 'G&G 14e, ch. 49',
      high_yield: true,
    },
    {
      id: 'loperamide',
      district: 'git',
      building: 'the opioid-gut antidiarrhoeal booth at the colonic transit control centre',
      class: 'Mu-opioid receptor agonist; peripheral antidiarrhoeal',
      mechanism: 'Activates mu-opioid receptors in the myenteric plexus of the small and large intestine. Stimulating these receptors reduces acetylcholine release → decreases intestinal peristalsis (increases segmental contractions, decreases propulsive movements) → slows intestinal transit → allows more time for fluid absorption → reduces stool frequency and liquidity. Also reduces intestinal secretion via enkephalinergic pathways. Does not cross the blood-brain barrier at therapeutic doses (P-glycoprotein efflux); no CNS opioid effects or analgesic effects at normal doses. At supratherapeutic doses: cardiac hERG channel blockade → QT prolongation and potentially fatal arrhythmia.',
      adverse_effects: 'Constipation; abdominal cramping; dry mouth; dizziness (rare at therapeutic doses); QT prolongation and arrhythmia at supratherapeutic doses; ileus if used in severe colitis or C. difficile infection (risk of toxic megacolon); rare hypersensitivity.',
      clinical_use: 'Acute diarrhoea (travellers\' diarrhoea, non-specific); chronic diarrhoea (IBS-D, short bowel syndrome); stoma output reduction. Avoid in bloody diarrhoea (possible invasive infection), severe colitis, and C. difficile.',
      memory_hook: 'Loperamide is the colonic slow-down valve — an opioid that stays outside the brain but grabs the intestinal emergency brake, reducing peristalsis without creating a high.',
      source: 'G&G 14e, ch. 49',
      high_yield: true,
    },
    {
      id: 'lactulose',
      district: 'git',
      building: 'the osmotic laxative cistern with the ammonia trap basement',
      class: 'Osmotic laxative; synthetic disaccharide',
      mechanism: 'Non-absorbable synthetic disaccharide (galactose + fructose). Not absorbed or digested in the small intestine. In the colon, colonic bacteria ferment lactulose to organic acids (lactic acid, acetic acid), lowering colonic pH and increasing osmolarity. The osmotic effect draws water into the colon, softening stool and stimulating peristalsis. In hepatic encephalopathy: the acidic colonic environment traps ammonia (NH3 + H+ → NH4+ which is poorly absorbed) → reduces blood ammonia; also reduces ammonia-producing bacterial load; also acts as a laxative to speed nitrogen elimination.',
      adverse_effects: 'Flatulence; bloating; abdominal cramping; nausea; diarrhoea (dose-dependent); electrolyte disturbance with prolonged excessive use.',
      clinical_use: 'Constipation; hepatic encephalopathy (first-line for both acute episodes and prevention of recurrence — targets to achieve 2–3 soft stools per day); hyperammonaemia reduction.',
      memory_hook: 'Lactulose does double duty — it pulls water into the bowel for laxation and simultaneously acidifies the colon to catch and trap ammonia before it returns to the brain.',
      source: 'G&G 14e, ch. 49',
      high_yield: true,
    },
    {
      id: 'bisacodyl',
      district: 'git',
      building: 'the stimulant laxative workshop at the colonic motor end of the market',
      class: 'Stimulant laxative; diphenylmethane derivative',
      mechanism: 'Taken orally or as suppository. The active metabolite (bis(p-hydroxyphenyl)-pyridyl-2-methane) acts directly on the colonic enteric nerve plexus and colonic mucosa to stimulate propulsive peristaltic contractions. Also alters water and electrolyte transport (reduces absorption, increases secretion) in the large intestine. Onset: oral 6–12 hours; suppository 15–60 minutes.',
      adverse_effects: 'Abdominal cramping; griping pain; nausea; electrolyte imbalance with chronic use; chronic use may cause melanosis coli (benign dark discolouration) and potentially laxative dependence; hypokalaemia with overuse.',
      clinical_use: 'Constipation (short-term); bowel preparation before colonoscopy or surgery (combined with osmotic agents); post-operative constipation; bedridden or opioid-induced constipation.',
      memory_hook: 'Bisacodyl is the stimulant whip in the colonic workshop — it fires the nerve plexus directly to drive propulsive contractions. Fast acting, but chronic cracking of the whip exhausts the colonic muscle.',
      source: 'G&G 14e, ch. 49',
      high_yield: false,
    },
    {
      id: 'senna',
      district: 'git',
      building: 'the herbal stimulant laxative stall near the traditional medicine corner',
      class: 'Stimulant laxative; anthraquinone glycoside',
      mechanism: 'Sennosides (anthraquinone glycosides derived from Senna alexandrina) are inactive prodrugs. Colonic bacteria cleave the glycoside bonds, releasing active anthraquinone metabolites (rhein-anthrone). These stimulate propulsive peristalsis via the myenteric plexus and inhibit colonic electrolyte and water absorption. The intact glycosides are not absorbed in the small intestine. Onset ~6–12 hours.',
      adverse_effects: 'Abdominal cramping; diarrhoea; electrolyte loss (hypokalaemia, hyponatraemia) with chronic use; melanosis coli (brownish-black discolouration of colonic mucosa — reversible); laxative dependency; potential hepatotoxicity with chronic high-dose use (rare).',
      clinical_use: 'Short-term constipation; opioid-induced constipation; bowel prep (in combination); palliative care constipation management.',
      memory_hook: 'Senna sends the colonic workforce the anthraquinone activation signal — the bacteria in the colon flip the switch and the peristaltic engine roars.',
      source: 'G&G 14e, ch. 49',
      high_yield: false,
    },
    {
      id: 'polyethylene_glycol',
      district: 'git',
      building: 'the bowel prep osmotic flush station at the colonoscopy preparation dock',
      class: 'Osmotic laxative; macrogol; non-absorbable polymer',
      mechanism: 'A high-molecular-weight polymer that is not absorbed, fermented, or metabolised in the GI tract. Holds water within the intestinal lumen through osmosis, softening stool and increasing faecal bulk and frequency. Unlike lactulose, does not cause significant fermentation or gas production. Iso-osmotic preparations (GoLYTELY-equivalent formulations) used for bowel prep do not cause net electrolyte shifts.',
      adverse_effects: 'Bloating; nausea; abdominal cramping; large-volume PEG solutions for bowel prep can cause nausea and aspiration risk in elderly; electrolyte disturbances with high-volume preparations (especially in renal impairment).',
      clinical_use: 'Constipation (first-line for chronic constipation in guidelines); bowel preparation before colonoscopy or GI surgery (large-volume iso-osmotic solutions); faecal impaction; overflow incontinence management; constipation in children.',
      memory_hook: 'Polyethylene glycol is the inert osmotic sponge — it traps water in the bowel without needing bacterial activation or causing gas, making it the gentlest and most reliable stool softener on market row.',
      source: 'G&G 14e, ch. 49',
      high_yield: true,
    },
    {
      id: 'cyclizine',
      district: 'git',
      building: 'the H1 antihistamine antiemetic caravan at the nausea junction',
      class: 'H1 antihistamine; anticholinergic; antiemetic',
      mechanism: 'Blocks histamine H1 receptors in the vomiting centre and vestibular nucleus in the brainstem. Also has significant muscarinic antagonist activity. Reduces afferent signals from the vestibular apparatus and reduces sensitivity of the emetic centre to vestibular and other emetic stimuli. Does not block D2 receptors — no prokinetic effect; no risk of EPS or tardive dyskinesia.',
      adverse_effects: 'Sedation (most common); dry mouth; blurred vision; urinary retention (anticholinergic effects); confusion in elderly (delirium — anticholinergic); constipation; rarely paradoxical excitation in children.',
      clinical_use: 'Nausea and vomiting from various causes (motion sickness, opioid-induced nausea, post-operative nausea, inner ear disorders); palliative care nausea; morning sickness of pregnancy (considered safe).',
      memory_hook: 'Cyclizine is the quiet antihistamine antiemetic — no EPS, no tardive dyskinesia, just mild anticholinergic sedation. The antidote to opioid nausea without crossing the D2 road.',
      source: 'G&G 14e, ch. 49',
      high_yield: true,
    },
    {
      id: 'prochlorperazine',
      district: 'git',
      building: 'the D2-antagonist antiemetic and vertigo treatment stall',
      class: 'Phenothiazine; D2 receptor antagonist; antiemetic and antivertigo agent',
      mechanism: 'Blocks D2 receptors predominantly in the chemoreceptor trigger zone (CTZ) in the area postrema (outside the blood-brain barrier) and in the vomiting centre. Also blocks histamine H1 receptors and alpha-1 adrenoceptors. The D2 blockade in the CTZ is the primary antiemetic mechanism. The antivertigo effect is mediated via vestibular nucleus D2 and H1 blockade.',
      adverse_effects: 'Extrapyramidal symptoms: acute dystonia (especially in young adults — treat with procyclidine or benztropine), akathisia, drug-induced parkinsonism; tardive dyskinesia (chronic use); hypotension (alpha-1 block); sedation; hyperprolactinaemia; rarely neuroleptic malignant syndrome; QT prolongation.',
      clinical_use: 'Nausea and vomiting from various causes (chemotherapy, post-operative, radiation, labyrinthitis); vertigo associated with vestibular disorders; migraine-associated nausea (often combined with analgesics in ED).',
      memory_hook: 'Prochlorperazine is the phenothiazine antiemetic that silences both the CTZ dopamine alarm and the vestibular disturbance signals — but it carries the EPS risk of the whole phenothiazine family.',
      source: 'G&G 14e, ch. 49',
      high_yield: true,
    },
    {
      id: 'mesalazine',
      district: 'git',
      building: 'the 5-ASA IBD anti-inflammatory wall-lining stall',
      class: '5-aminosalicylate (5-ASA); topical intestinal anti-inflammatory',
      mechanism: 'The active moiety is 5-aminosalicylic acid (mesalazine/mesalamine). Acts topically within the gut lumen. Mechanism: inhibits prostaglandin and leukotriene synthesis in intestinal mucosa (inhibits COX and 5-LOX); activates nuclear peroxisome proliferator-activated receptor gamma (PPAR-γ) → anti-inflammatory transcription; reduces mucosal NF-κB activation. Must be delivered to the affected bowel segment — various formulations release drug in the terminal ileum or colon. For UC: suppositories/enemas for distal disease, oral for extensive disease. Sulfasalazine is the prodrug (5-ASA linked to sulfapyridine) — colonic bacteria cleave the azo bond; sulfapyridine is the side-effect carrier.',
      adverse_effects: 'Generally well tolerated; headache; nausea; diarrhoea; rare: nephrotoxicity (interstitial nephritis — monitor renal function); rare hepatotoxicity; rare mesalazine-induced colitis (paradoxical). Sulfasalazine form: sulfa allergy risk; oligospermia (reversible, sulfapyridine-mediated); folate deficiency (blocks dihydropteroate synthase).',
      clinical_use: 'Ulcerative colitis — first-line for mild-to-moderate disease (induction and maintenance); Crohn\'s disease of the colon (less evidence than UC); post-surgical maintenance in UC.',
      memory_hook: 'Mesalazine lines the intestinal wall with anti-inflammatory protection — it works topically where it lands, not systemically, and its prodrug sulfasalazine carries the sulfapyridine side-effect rucksack.',
      source: 'G&G 14e, ch. 49',
      high_yield: true,
    },
    {
      id: 'adalimumab',
      district: 'git',
      building: 'the anti-TNF biological tower at the IBD immunological precinct',
      class: 'Anti-TNF-alpha monoclonal antibody; fully human IgG1',
      mechanism: 'Fully human monoclonal antibody that binds soluble and transmembrane TNF-alpha with high affinity, preventing TNF-alpha from engaging its receptors (TNFR1 and TNFR2). TNF-alpha is a central pro-inflammatory cytokine in IBD — drives mucosal inflammation, epithelial barrier disruption, and ulceration. Blocking TNF-alpha reduces mucosal inflammation, promotes mucosal healing, and induces and maintains clinical remission. Can also fix complement and lyse TNF-expressing cells via ADCC.',
      adverse_effects: 'Reactivation of latent tuberculosis (screen with Mantoux/IGRA + CXR before treatment and annually); reactivation of hepatitis B (screen HBsAg, HBcAb before treatment); increased risk of opportunistic infections (fungal, bacterial, viral); injection-site reactions; paradoxical worsening of psoriasis or inflammatory arthritis; demyelinating disease (rare); heart failure exacerbation (avoid in moderate-severe HF); malignancy risk (lymphoma — especially hepatosplenic T-cell lymphoma with combination thiopurine therapy).',
      clinical_use: 'Moderate-to-severe Crohn\'s disease and ulcerative colitis not controlled by conventional therapy; rheumatoid arthritis; psoriatic arthritis; ankylosing spondylitis; psoriasis; juvenile idiopathic arthritis.',
      memory_hook: 'Adalimumab is the anti-TNF siege-breaker that calms the mucosal war — but it must screen for TB and hepatitis B before entering the city gates, since it also disarms the normal infection watchmen.',
      source: 'G&G 14e, ch. 49',
      high_yield: true,
    },
    {
      id: 'vedolizumab',
      district: 'git',
      building: 'the gut-selective integrin blockade berth at the IBD biological precinct',
      class: 'Anti-alpha4beta7 integrin monoclonal antibody; gut-selective; humanised IgG1',
      mechanism: 'Binds the alpha4beta7 integrin heterodimer on gut-homing lymphocytes (T cells). Alpha4beta7 interacts with mucosal addressin cell adhesion molecule-1 (MAdCAM-1) on intestinal endothelium, mediating lymphocyte trafficking specifically into the GI mucosa. Blocking this interaction prevents lymphocyte recruitment into the gut mucosa, reducing intestinal inflammation. The selectivity for gut homing (rather than all lymphocyte trafficking) results in a lower systemic immunosuppression profile than anti-TNF agents — no increase in TB or systemic infections reported.',
      adverse_effects: 'Nasopharyngitis; arthralgia; headache; infusion reactions; hypersensitivity; PML has not been reported (unlike natalizumab, which blocks both gut and CNS lymphocyte homing); infection rates not significantly elevated above placebo in clinical trials.',
      clinical_use: 'Moderate-to-severe ulcerative colitis and Crohn\'s disease; favoured in patients with prior anti-TNF failure; also suitable for patients where infections from anti-TNF therapy are a concern (e.g., elderly, concurrent immunosuppression).',
      memory_hook: 'Vedolizumab is the gut bouncer — it only blocks the lymphocyte gate that leads specifically into the gut mucosa, leaving all other immune checkpoints open and earning its reputation as the well-tolerated biological.',
      source: 'G&G 14e, ch. 49',
      high_yield: true,
    },
  ],
};

if (typeof window !== 'undefined') window.DISTRICT_GIT = DISTRICT_GIT;
