const DISTRICT_TOXICOLOGY = {
  id: 'toxicology',
  name: 'Toxicology',
  theme_line: 'Hazmat silo · poisons + antidotes outside the wall',
  walkthrough: `The Toxicology district lies beyond the outer wall of Pharmacology City — a ring of hazmat silos, antidote bunkers, and emergency response stations clustered where the poisons come in and the antidotes go out. Every building in this district is a monument to a specific poisoning, and every antidote is the architectural mirror image of its toxin.

The biggest bunker belongs to n-acetylcysteine, the paracetamol (acetaminophen) antidote. Inside, the Rumack-Matthew nomogram chart covers an entire wall — a plot of plasma paracetamol concentration against time from ingestion, with the treatment line running diagonally across it. Above a certain threshold, paracetamol's minor toxic metabolite NAPQI overwhelms hepatic glutathione stores and begins alkylating liver proteins. NAC replenishes glutathione before the damage becomes irreversible.

Next door, the naloxone depot operates around the clock — a high-rotation station aware that its product's half-life is shorter than most opioid agonists, meaning a patient can wake up, seem fine, and then relapse into respiratory arrest when the naloxone wears off. The repeat-dose warning is painted in red above the doorway.

Flumazenil's booth carries a different kind of warning: two crossed-out symbols representing benzodiazepine-dependent patients and TCA co-ingestion. In both settings, giving flumazenil can precipitate catastrophic seizures. Its short half-life gives it the same re-sedation risk as naloxone.

The chelation wing occupies the southern end of the district — heavy metal remediation facilities for iron (deferoxamine), arsenic/mercury/gold (dimercaprol/BAL), lead (succimer for children, EDTA-calcium for severe encephalopathy), and cyanide (hydroxocobalamin). The methylene blue silo is marked with a large G6PD warning diamond — it cannot be used in G6PD-deficient patients, in whom it would cause haemolytic anaemia rather than cure methaemoglobinaemia.`,
  palette: { ground: 0xB8A080, accent: 0xFF6B35, water: 0x5A8A6A },
  position: { x: 60, z: -25 },
  drugs: [
    {
      id: 'n_acetylcysteine',
      district: 'toxicology',
      building: 'the glutathione replenishment bunker at the paracetamol antidote headquarters',
      class: 'Glutathione precursor; antidote for paracetamol (acetaminophen) overdose',
      mechanism: 'Paracetamol overdose generates excess NAPQI (N-acetyl-p-benzoquinone imine) via CYP2E1 and CYP3A4 oxidative metabolism; NAPQI depletes hepatic glutathione and covalently binds hepatocyte proteins → hepatic necrosis. N-acetylcysteine (NAC) provides cysteine as a glutathione precursor, replenishing glutathione stores to detoxify NAPQI. Also directly conjugates with NAPQI. Given IV as a three-bag infusion protocol (loading dose, then two maintenance infusions over 21 hours) or orally. Treatment guided by the Rumack-Matthew nomogram — NAC indicated when plasma paracetamol level falls above the treatment line relative to time post-ingestion.',
      adverse_effects: 'IV form: anaphylactoid reaction (flushing, urticaria, bronchospasm, hypotension — particularly common with the loading infusion; treat by slowing or briefly stopping the infusion and giving antihistamine; resume at lower rate); nausea and vomiting (especially oral form); rarely true anaphylaxis.',
      clinical_use: 'Paracetamol overdose (most common indication); fulminant hepatic failure (non-paracetamol cause — improves transplant-free survival). Also used as mucolytic in respiratory disease (see Respiratory district) and as cytoprotectant in contrast nephropathy prevention (limited evidence).',
      memory_hook: 'NAC is the glutathione resupply truck — when paracetamol\'s toxic metabolite NAPQI has emptied the liver\'s defence warehouse, NAC rushes in with the raw material to rebuild it, guided by the Rumack-Matthew map.',
      source: 'G&G 14e, ch. 4',
      high_yield: true,
    },
    {
      id: 'naloxone',
      district: 'toxicology',
      building: 'the high-rotation opioid reversal depot with the re-dosing alarm',
      class: 'Opioid receptor antagonist; pure competitive antagonist',
      mechanism: 'Competitively antagonises mu, kappa, and delta opioid receptors with high affinity, rapidly displacing opioid agonists from their binding sites. Rapidly reverses opioid-induced respiratory depression, sedation, and miosis. Onset within 2–5 minutes IV. Critical limitation: shorter half-life than most opioid agonists (elimination half-life ~60–90 minutes) — patient may relapse into respiratory depression as naloxone dissipates while the agonist (e.g., methadone, sustained-release morphine) remains bound. Repeat dosing or continuous infusion may be required.',
      adverse_effects: 'Precipitates acute opioid withdrawal syndrome in opioid-dependent patients — agitation, sweating, piloerection, vomiting, diarrhoea, tachycardia, hypertension (potentially severe); pulmonary oedema (rare, mechanism unclear); re-narcotisation risk if not monitored; rare: ventricular arrhythmias in susceptible patients.',
      clinical_use: 'Opioid overdose (IV, IM, intranasal); reversal of opioid-induced respiratory depression post-operatively; suspected opioid overdose in unresponsive patients; neonatal respiratory depression from maternal opioid use. Intranasal naloxone (higher-concentration formulations) for community use.',
      memory_hook: 'Naloxone wins the receptor race against all opioids — it kicks them off the mu receptor in minutes. But it leaves the track before the slower opioids, so the race result can reverse without you noticing.',
      source: 'G&G 14e, ch. 4',
      high_yield: true,
    },
    {
      id: 'flumazenil',
      district: 'toxicology',
      building: 'the benzodiazepine reversal station with the seizure-risk gate',
      class: 'Benzodiazepine receptor antagonist; GABA-A receptor modulator antagonist',
      mechanism: 'Competitive antagonist at the benzodiazepine binding site on GABA-A receptors. Rapidly reverses benzodiazepine-induced CNS and respiratory depression. Onset within 1–2 minutes IV. Short half-life (~1 hour) — much shorter than long-acting benzodiazepines (diazepam, chlordiazepoxide); re-sedation is common. Critically limited by two absolute contraindications: (1) Benzodiazepine-dependent patients: abrupt reversal of chronic BZD effect precipitates severe withdrawal seizures, potentially status epilepticus. (2) TCA co-ingestion: in tricyclic antidepressant overdose, benzodiazepines protect against TCA-induced convulsions; flumazenil removes this protection → seizures plus the TCA\'s sodium-channel blockade → fatal arrhythmia may follow.',
      adverse_effects: 'Re-sedation (common, due to short half-life); acute BZD withdrawal seizures (if BZD-dependent); nausea; headache; palpitations; anxiety; convulsions in epileptic patients maintained on BZDs.',
      clinical_use: 'Reversal of procedural (diagnostic) benzodiazepine sedation in monitored settings; investigational reversal of acute benzodiazepine overdose only when CI are absent. NOT routinely used in mixed-drug overdoses or chronic BZD use.',
      memory_hook: 'Flumazenil unbolts the BZD lock in minutes — but it leaves before the benzodiazepine, so re-sedation awaits, and in a dependent patient it triggers the seizure alarm by removing the GABA buffer.',
      source: 'G&G 14e, ch. 4',
      high_yield: true,
    },
    {
      id: 'digoxin_fab',
      district: 'toxicology',
      building: 'the digoxin-specific antibody Fab fragment neutralisation silo',
      class: 'Digoxin-specific antibody Fab fragments; antidote for digoxin toxicity',
      mechanism: 'Ovine-derived Fab fragments (digoxin immune Fab) with high affinity for digoxin (and digitoxin). Bind free serum digoxin, preventing it from engaging the Na+/K+-ATPase pump. The drug-Fab complex is renally excreted. Rapidly reverses digoxin toxicity: hyperkalemia, bradyarrhythmias, heart block, ventricular arrhythmias. Dosing calculated based on the amount of digoxin to be neutralised (body load estimate from serum level or number of tablets ingested).',
      adverse_effects: 'Hypokalaemia (after treatment — as digoxin\'s Na+/K+-ATPase inhibition is reversed, cellular K+ uptake increases → serum K+ falls; monitor carefully); worsening heart failure (digitalising effect removed); allergic reactions (rare, given ovine origin); rarely anaphylaxis.',
      clinical_use: 'Life-threatening digoxin toxicity: severe bradycardia or high-degree heart block; ventricular arrhythmias (ventricular tachycardia, fibrillation); severe hyperkalaemia (> 5.5 mEq/L with toxicity); haemodynamic instability. Also for digitoxin toxicity.',
      memory_hook: 'Digoxin-specific Fab is the molecular sponge that mops up free digoxin from the blood — each Fab fragment wraps around one digoxin molecule and the whole bundle is expelled in the urine.',
      source: 'G&G 14e, ch. 4',
      high_yield: true,
    },
    {
      id: 'atropine_pralidoxime',
      district: 'toxicology',
      building: 'the organophosphate antidote double-bay station: atropine and 2-PAM',
      class: 'Organophosphate antidotes: muscarinic antagonist + AChE reactivator',
      mechanism: 'Organophosphate (OP) poisoning (nerve agents, pesticides) irreversibly phosphorylates acetylcholinesterase → accumulation of ACh at all cholinergic synapses → SLUDGE (muscarinic) + nicotinic crisis (fasciculations, paralysis) + CNS effects (seizures). ATROPINE: competitively blocks muscarinic receptors → reverses secretions, bronchospasm, bradycardia, miosis (muscarinic effects). Large, repeated doses are typically needed. Does NOT reverse NMJ paralysis. PRALIDOXIME (2-PAM): an oxime that attacks the phosphoryl-enzyme complex, cleaving the phosphoryl group from AChE\'s serine → reactivates AChE. Effective primarily at the NMJ (reverses nicotinic effects, respiratory muscle paralysis). MUST be given early, before "aging" (further dealkylation of the phosphoryl-enzyme bond) makes reactivation impossible. Aging rate varies: very rapid with soman (minutes), slower with parathion (hours).',
      adverse_effects: 'Atropine: tachycardia; hyperthermia; urinary retention; CNS anticholinergic toxidrome (dry as a bone, etc.) — aim for titrated reversal of secretions without causing toxidrome. Pralidoxime: dizziness; headache; blurred vision; nausea; tachycardia; hypertension; at high infusion rates: respiratory arrest (rare).',
      clinical_use: 'Organophosphate poisoning (agricultural, industrial, and nerve agent exposure). Atropine is the immediate priority (reverse secretions and bronchospasm to prevent asphyxia); pralidoxime must be given as soon as possible to reactivate AChE before aging occurs.',
      memory_hook: 'Atropine hoses down the muscarinic flood and pralidoxime unbolds the phosphoryl padlock from AChE before it rusts shut — they are the two-tool emergency kit for the organophosphate catastrophe.',
      source: 'G&G 14e, ch. 4',
      high_yield: true,
    },
    {
      id: 'deferoxamine',
      district: 'toxicology',
      building: 'the parenteral iron chelation pump station at the iron overdose silo',
      class: 'Iron chelating agent; siderophore-based chelator',
      mechanism: 'A siderophore (produced by Streptomyces pilosus) with very high affinity for ferric iron (Fe3+). Forms a stable, water-soluble ferrioxamine complex with free and loosely bound iron in the circulation and tissues. Ferrioxamine is renally excreted → urine turns orange-red (vin rosé colour, a sign of iron chelation). Does not chelate iron already incorporated into haemoglobin or myoglobin. Given parenterally (IV preferred in severe poisoning; IM in moderate poisoning).',
      adverse_effects: 'Hypotension with rapid IV infusion (must give slowly); injection-site reactions; flushing; urticaria; rarely anaphylaxis; with prolonged or high-dose use: pulmonary toxicity; Yersinia enterocolitica infections (iron provides bacterial nutrition — deferoxamine may facilitate Yersinia septicaemia); ocular and auditory toxicity (chronic use).',
      clinical_use: 'Acute iron poisoning (particularly in children) — when serum iron levels are high or there are signs of systemic toxicity (metabolic acidosis, shock, altered consciousness); haemochromatosis — limited role, desferrioxamine less preferred than oral chelators for long-term iron overload.',
      memory_hook: 'Deferoxamine is the molecular siderophore bucket — it scavenges free iron from the blood and tissues, turning urine rose-red as it dumps its iron cargo in the renal drain.',
      source: 'G&G 14e, ch. 4',
      high_yield: true,
    },
    {
      id: 'dimercaprol',
      district: 'toxicology',
      building: 'the BAL heavy metal chelation clinic for arsenic, mercury, and gold poisoning',
      class: 'Heavy metal chelating agent; dithiol compound; British Anti-Lewisite (BAL)',
      mechanism: 'A dithiol compound: two sulfhydryl (thiol) groups on adjacent carbons form stable chelate rings with heavy metal ions. Binds arsenic, mercury (inorganic), gold, lead (as adjunct), and antimony; the metal-BAL complex is water-soluble and excreted in urine and bile. The compound competes with and prevents heavy metals from binding to tissue enzymes (particularly sulfhydryl-dependent enzymes → toxic effects are from enzyme inhibition). Does NOT chelate iron, cadmium, selenium, or organic mercury effectively. Given IM (oil-based formulation).',
      adverse_effects: 'Pain at injection site; nausea; vomiting; headache; burning sensation in lips, mouth, throat; hypertension and tachycardia; lacrimation; sweating; fever in children; alkaline urine is required (keep urine pH > 7) to prevent redistribution of the metal-BAL complex (especially mercury) to the brain from acid urine; haemolytic anaemia in G6PD deficiency.',
      clinical_use: 'Arsenic poisoning (first-line); inorganic mercury poisoning; gold toxicity; lead encephalopathy (first-line, often given before EDTA-calcium); antimony poisoning.',
      memory_hook: 'Dimercaprol is the original metal trapper — its two sulfur arms grab arsenic and mercury in an inescapable dithiol hug, making the complex water-soluble for excretion. Developed as an antidote to Lewisite nerve agent in World War II.',
      source: 'G&G 14e, ch. 4',
      high_yield: true,
    },
    {
      id: 'succimer',
      district: 'toxicology',
      building: 'the oral paediatric lead chelation clinic at the DMSA wing',
      class: 'Heavy metal chelating agent; oral dithiosuccinic acid (DMSA)',
      mechanism: 'Meso-2,3-dimercaptosuccinic acid (DMSA/succimer) — a water-soluble oral dithiol chelating agent. Chelates lead (and arsenic, mercury, cadmium) by forming stable water-soluble complexes with the metal ions via its two thiol groups. The metal-DMSA chelate is renally excreted. More selective and less toxic than dimercaprol; does not significantly increase faecal metal excretion or remove essential metals (zinc, iron, copper) to the same extent. Well absorbed orally.',
      adverse_effects: 'Nausea; vomiting; diarrhoea; transient elevation of liver enzymes; sulphurous (egg-like) odour of breath and urine; rash; rarely: mild neutropenia or thrombocytopenia; does not redistribute lead to the brain (safer than dimercaprol in this regard).',
      clinical_use: 'Lead poisoning in children (blood lead levels indicating treatment, typically symptomatic or persistently elevated levels) — first-line oral chelator for paediatric lead toxicity; also arsenic and mercury poisoning (as alternative to dimercaprol).',
      memory_hook: 'Succimer is the child-safe lead chelator — an oral pill with a two-sulfur grip that pulls lead out gently without sending it to the brain or depleting the body\'s vital metals.',
      source: 'G&G 14e, ch. 4',
      high_yield: true,
    },
    {
      id: 'edta_calcium',
      district: 'toxicology',
      building: 'the intravenous lead encephalopathy treatment bay',
      class: 'Heavy metal chelating agent; calcium disodium EDTA (edetate calcium disodium)',
      mechanism: 'Calcium disodium EDTA (calcium disodium edetate) — calcium in the complex is displaced by lead (and other divalent metals with higher EDTA affinity: zinc, manganese, copper, cadmium, mercury). The metal-EDTA chelate is hydrophilic and renally excreted. MUST use the calcium form (not the disodium form alone) to avoid fatal hypocalcaemia. IV administration. Cannot cross the blood-brain barrier — predominantly chelates lead in blood, bone, and soft tissues.',
      adverse_effects: 'Nephrotoxicity (proximal tubular damage — dose-dependent; ensure adequate hydration and monitor renal function); hypocalcaemia if incorrect form used; zinc depletion with prolonged use; fever; malaise; pain at injection site; potential redistribution of lead into CNS (reason to pretreat with dimercaprol first in encephalopathy).',
      clinical_use: 'Severe lead poisoning with encephalopathy (typically after initial dimercaprol to prevent redistribution into CNS); symptomatic lead poisoning in children when blood lead level is very elevated; used after dimercaprol pretreatment in lead encephalopathy.',
      memory_hook: 'EDTA-calcium is the intravenous lead vacuum — it pulls lead from the blood and bones into a hydrophilic chelate for renal excretion, but always let dimercaprol go in first when the brain is involved.',
      source: 'G&G 14e, ch. 4',
      high_yield: false,
    },
    {
      id: 'methylene_blue',
      district: 'toxicology',
      building: 'the methaemoglobinaemia treatment silo with the G6PD exclusion gate',
      class: 'Methaemoglobinaemia antidote; electron carrier; thiazine dye',
      mechanism: 'Methaemoglobin (MetHb) contains ferric iron (Fe3+) instead of ferrous (Fe2+) — it cannot carry oxygen, producing a functional anaemia and characteristic chocolate-brown blood. Causes: nitrites, dapsone, benzocaine, prilocaine, nitrofurantoin. Methylene blue (MB) is reduced by NADPH (generated by G6PD via the hexose monophosphate shunt) to leucomethylene blue, which then reduces MetHb back to oxyhaemoglobin. G6PD deficiency: the reduction of MB to leucomethylene blue cannot occur — MB itself is pro-oxidant and worsens MetHb and causes haemolytic anaemia → methylene blue is CONTRAINDICATED in G6PD deficiency.',
      adverse_effects: 'Nausea; vomiting; dizziness; headache; pain on injection; blue discolouration of urine and skin; haemolytic anaemia in G6PD-deficient patients (absolute CI); at excessive doses: paradoxical methaemoglobinaemia (MB itself has oxidant potential at high doses); serotonin syndrome risk if combined with serotonergic drugs (MB inhibits MAO-A).',
      clinical_use: 'Symptomatic methaemoglobinaemia from any cause when G6PD is normal; also used in parathyroid and parathyroid-related surgery to visually mark parathyroid tissue (chromophore property). For G6PD-deficient patients: hyperbaric oxygen or exchange transfusion instead.',
      memory_hook: 'Methylene blue is the electron shuttle that reverses methaemoglobinaemia — but it needs NADPH from G6PD to charge up. Without G6PD, the shuttle runs empty and becomes a weapon, making things worse.',
      source: 'G&G 14e, ch. 4',
      high_yield: true,
    },
    {
      id: 'fomepizole',
      district: 'toxicology',
      building: 'the alcohol dehydrogenase blockade bunker for methanol and ethylene glycol poisoning',
      class: 'Alcohol dehydrogenase inhibitor; antidote for methanol and ethylene glycol poisoning',
      mechanism: 'Competitively inhibits alcohol dehydrogenase (ADH) — the enzyme that oxidises methanol to formaldehyde (→ formic acid → optic nerve and CNS toxicity) and ethylene glycol to glycolaldehyde (→ glycolic acid → oxalic acid → calcium oxalate crystals in kidneys → renal failure). By blocking ADH, fomepizole prevents production of the toxic metabolites, buying time for renal excretion or haemodialysis to eliminate the parent alcohol. Has high affinity for ADH (Ki ~0.1 μM vs. ethanol ~1 mM).',
      adverse_effects: 'Nausea; headache; dizziness; injection-site reactions; mild elevation of liver enzymes; metallic taste; rarely: tachycardia, hypotension. Generally well tolerated.',
      clinical_use: 'Methanol poisoning; ethylene glycol poisoning — initiated promptly when toxic alcohol ingestion confirmed or strongly suspected (high anion gap metabolic acidosis + osmol gap); reduces need for ethanol infusion (older therapy with more side effects). Often combined with haemodialysis in severe cases.',
      memory_hook: 'Fomepizole is the ADH gatekeeper lock — it prevents methanol and ethylene glycol from being converted to their organ-destroying metabolites, giving the body or dialysis time to clear the poison intact.',
      source: 'G&G 14e, ch. 4',
      high_yield: true,
    },
    {
      id: 'hydroxocobalamin',
      district: 'toxicology',
      building: 'the cyanide and smoke inhalation antidote vault',
      class: 'Cyanide antidote; vitamin B12 precursor analogue',
      mechanism: 'Cyanide (from hydrogen cyanide gas, fires, nitroprusside metabolism, cyanogenic compounds) binds cytochrome c oxidase in the mitochondrial electron transport chain → inhibits cellular respiration → histotoxic hypoxia (cells cannot use oxygen → lactate accumulates → severe lactic acidosis; "cherry red" venous blood). Hydroxocobalamin binds cyanide ions with high affinity, forming cyanocobalamin (vitamin B12) which is non-toxic and renally excreted. Does not compromise oxygen-carrying capacity (unlike methemoglobin-forming agents). The complex is pink-red coloured → transiently discolours urine and skin red.',
      adverse_effects: 'Red discolouration of skin, mucous membranes, and urine (transient); hypertension (vasoconstricting effect); headache; nausea; interference with pulse oximetry and co-oximetry readings; interference with certain lab measurements (chromogenic assays) for 48–72 hours.',
      clinical_use: 'Cyanide poisoning (smoke inhalation in enclosed-space fires, deliberate exposure, nitroprusside-associated cyanide toxicity); pre-hospital and empirical treatment of smoke inhalation victims in combination with treatment for carbon monoxide poisoning. Preferred over older methemoglobin-forming antidotes (amyl nitrite, sodium nitrite) when CO poisoning may coexist, as it does not reduce oxygen-carrying capacity.',
      memory_hook: 'Hydroxocobalamin is the vitamin-B12 cyano-sponge — it swallows cyanide molecules and turns them into harmless B12 for the kidneys, leaving the body\'s oxygen transport system fully intact.',
      source: 'G&G 14e, ch. 4',
      high_yield: true,
    },
    {
      id: 'glucagon',
      district: 'toxicology',
      building: 'the cAMP rescue station for beta-blocker and CCB overdose',
      class: 'Glucagon (endogenous hormone used as antidote); cAMP-elevating agent',
      mechanism: 'In beta-blocker overdose, beta-adrenoceptors are blocked, preventing catecholamine-mediated cAMP elevation in cardiac cells → bradycardia, hypotension, negative inotropy. Glucagon activates a separate glucagon receptor (different G-protein pathway from beta-receptors) → adenylyl cyclase activation → cAMP elevation → positive chronotropy and inotropy, independent of beta-adrenoceptors. Thus glucagon bypasses the beta-blocker block. In calcium channel blocker overdose: glucagon raises cAMP → increased calcium influx through L-type channels, partially compensating for CCB blockade.',
      adverse_effects: 'Nausea and vomiting (common — have airway protection ready to prevent aspiration in obtunded patient); hyperglycaemia; hypokalaemia; large doses are required for effect; tachycardia; insulin release at lower doses (pancreatic glucagon receptors).',
      clinical_use: 'Beta-blocker overdose (bradycardia, hypotension not responding to atropine and IV fluids); calcium channel blocker overdose (adjunct, less effective than high-dose insulin-dextrose therapy); hypoglycaemia (IM or intranasal in conscious patients unable to take oral glucose).',
      memory_hook: 'Glucagon is the side door into the cardiac cAMP factory — when beta-blockers have barricaded the front entrance, glucagon walks in through its own receptor and kicks the cAMP production back into action.',
      source: 'G&G 14e, ch. 4',
      high_yield: true,
    },
    {
      id: 'calcium_gluconate',
      district: 'toxicology',
      building: 'the calcium depot station for CCB overdose and hyperkalaemia management',
      class: 'Calcium salt; membrane-stabilising agent; antidote for calcium channel blocker overdose and hyperkalaemia',
      mechanism: 'Calcium channel blocker (CCB) overdose: provides calcium to overcome the CCB\'s competition at L-type calcium channels in cardiac and vascular smooth muscle — raising extracellular calcium concentration drives more calcium through any residual unblocked channels. Hyperkalaemia: calcium antagonises the effect of high potassium on cardiac membrane excitability — raises the threshold potential, stabilising the myocardium against arrhythmia within 1–3 minutes. Does NOT lower serum K+ — other measures (insulin-dextrose, salbutamol, resonium) are needed to reduce K+. Rapid onset of cardioprotective effect.',
      adverse_effects: 'Hypercalcaemia with excess dosing; bradycardia if given too rapidly IV (calcium bolus); tissue necrosis if extravasation occurs (calcium gluconate less caustic than calcium chloride); constipation (oral); nausea.',
      clinical_use: 'Symptomatic hyperkalaemia (ECG changes — peaked T waves, widened QRS, sinusoidal pattern) — immediate stabilisation; calcium channel blocker overdose — high-dose calcium therapy; hypocalcaemia; hypermagnesaemia; hydrofluoric acid burns (topical and IV).',
      memory_hook: 'Calcium gluconate is the cardiac circuit breaker reset — in hyperkalaemia it restabilises the membrane potential instantly (without changing K+ levels), and in CCB overdose it competes for the channels the blocker has hijacked.',
      source: 'G&G 14e, ch. 4',
      high_yield: false,
    },
  ],
};

if (typeof window !== 'undefined') window.DISTRICT_TOXICOLOGY = DISTRICT_TOXICOLOGY;
